### ISSUE TITLE
please add the amd version

### ISSUE THREAD

**Issue by jonsee** [xmrig/xmrig-nvidia#1]
please add the amd version

**Comment by psddp** [comment]
+1

**Comment by calvintam236** [comment]
+1
@xmrig any progress on the AMD version yet?

**Comment by mxjoe** [comment]
+1

**Comment by lexphor** [comment]
+1

**Comment by xmrig** [comment]
I create roadmap for next releases #106

**Comment by xDESTROYx** [comment]
+1

**Comment by lamba84** [comment]
+1, so far the best miner I used both in Linux & windows for CPU and nvidia GPU, would be great to have for AMD GPU too

**Comment by gigi2006** [comment]
+1

**Comment by elisaado** [comment]
+1 I'd totally enable donations as well

**Comment by xmrig** [comment]
AMD version now available https://github.com/xmrig/xmrig-amd
It stable, all features from v2.4.2 included, but still beta version.
Thank you.
