### ISSUE TITLE
Is it possible to build on window too?

### ISSUE THREAD

**Issue by psddp** [xmrig/xmrig-nvidia#10]
Is it possible to support build on window too?

**Comment by xbhuang1994** [comment]
```
mkdir build
cd build
cmake .. -G "Visual Studio 15 2017 Win64" -T v140_xp -DCMAKE_BUILD_TYPE=Release -DUV_INCLUDE_DIR=c:\<path>\libuv\include -DUV_LIBRARY=c:\<path>\libuv\Release\lib\libuv.lib
```
It will create Visual Studio Solution file xmrig-nvidia.sln

**Comment by dorimanx** [comment]
tried to build in MSYS2_64
cmake .. -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DUV_INCLUDE_DIR="e:\msys64\mingw64\include" -DUV_LIBRARY="e:\msys64\mingw64\lib\libuv.a" -DCUDA_ARCH="20;30;50"

but make fail:
Dorimanx@My-PC MINGW64 ~/xmrig-nvidia/build
$ make
[  2%] Building NVCC (Device) object CMakeFiles/xmrig-cuda.dir/src/nvidia/xmrig-cuda_generated_cuda_extra.cu.obj
nvcc fatal   : Host compiler targets unsupported OS.
CMake Error at xmrig-cuda_generated_cuda_extra.cu.obj.Release.cmake:222 (message):
  Error generating
  E:/msys64/home/Dorimanx/xmrig-nvidia/build/CMakeFiles/xmrig-cuda.dir/src/nvidia/./xmrig-cuda_generated_cuda_extra.cu.obj


make[2]: *** [CMakeFiles/xmrig-cuda.dir/build.make:72: CMakeFiles/xmrig-cuda.dir/src/nvidia/xmrig-cuda_generated_cuda_extra.cu.obj] Error 1
make[1]: *** [CMakeFiles/Makefile2:67: CMakeFiles/xmrig-cuda.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

**Comment by esfomeado** [comment]
@dorimanx Install CMake for windows and use the commands stated by @xbhuang1994.
Then compile using Visual Studio 2015.

**Comment by djfinch** [comment]
Hi guys,

I know, how-to is in roadmap but i'm still getting this:
![scr](https://user-images.githubusercontent.com/13107713/30446501-a94325be-9989-11e7-942c-dc2a4444538d.PNG)

CUDA_SDK_ROOT error is probably minor (maybe I forgot to install it) but I dont know how to solve MHD_LIBRARY error. :/

Thanks for help...

**Comment by xmrig** [comment]
You trying to build dev branch, please use master branch or remove this line https://github.com/xmrig/xmrig-nvidia/blob/master/CMakeLists.txt#L140

Looks like WITH_HTTPD broken, I will fix it.
Thank you.

**Comment by djfinch** [comment]
Ah, sorry, I forgot to switch back from dev to master... I suppose CUDA SDK is not needed but should be somewhere in "ProgramData" on Win10. I'm doing it in VBOX and believe physical card is not needed to successful build. VBOX was stuck during build yesterday but I will try it once again today. (Win10 in VBOX, VS2017 Community, latest CMAKE, latest libUV, static build, git clone + nothing changed inside the code, AEON off)

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig-nvidia/wiki/Windows-Build
