### ISSUE TITLE
What to do after the xmrig-nvidia.sln is compiled on Windows

### ISSUE THREAD

**Issue by rsxdan** [xmrig/xmrig-nvidia#104]
Hi guys,

I'm no programmer and new to this and I don't know what to do after I compiled the **xmrig-nvidia.sln** file. I followed the Wiki page and it worked great but I don't know what to do after the Compile section. I tried to build it up in Visual Studio but I always get errors. I might be doing something wrong.

Can you guys help me please?

Thanks.

**Comment by metalurgus** [comment]
This means that yoi probably do something wrong. Show which errors exacrly you get, if you want to know what exactly is wrong

**Comment by rsxdan** [comment]
Ok I'll let you know the error soon as I'll be home in around 1 hour. But let me recap first. So I'll open the xmrig-nvidia.sln file using Visual Studio, then select the solution on the right panel, right-click and select Build or Build Solution? I just don't know how to use Visual Studio.

Will this link help me?
https://msdn.microsoft.com/en-us/library/5tdasz7h.aspx

**Comment by rsxdan** [comment]
So this is the error I get when I try to **Build > Project Only > xmrig-nvidia**

1>------ Rebuild All started: Project: xmrig-nvidia, Configuration: Release x64 ------
1>Building Custom Rule C:/Mining/xmrig-nvidia-master/CMakeLists.txt
1>CMake does not need to re-run because C:/Mining/xmrig-nvidia-master/build/CMakeFiles/generate.stamp is up-to-date.
1>Api.cpp
1>C:\Mining\xmrig-nvidia-master\src\api/Api.h(29): fatal error C1083: Cannot open include file: 'uv.h': No such file or directory
1>ApiState.cpp
1>C:\Mining\xmrig-nvidia-master\src\api\ApiState.cpp(26): fatal error C1083: Cannot open include file: 'uv.h': No such file or directory
1>NetworkState.cpp
1>C:\Mining\xmrig-nvidia-master\src\api\NetworkState.cpp(27): fatal error C1083: Cannot open include file: 'uv.h': No such file or directory
1>App.cpp
1>C:\Mining\xmrig-nvidia-master\src\App.cpp(26): fatal error C1083: Cannot open include file: 'uv.h': No such file or directory
1>Console.cpp
1>c:\mining\xmrig-nvidia-master\src\Console.h(28): fatal error C1083: Cannot open include file: 'uv.h': No such file or directory
1>Cpu_stub.cpp
1>ConsoleLog.cpp
1>C:\Mining\xmrig-nvidia-master\src\log/ConsoleLog.h(28): fatal error C1083: Cannot open include file: 'uv.h': No such file or directory
1>FileLog.cpp
1>C:\Mining\xmrig-nvidia-master\src\log/FileLog.h(28): fatal error C1083: Cannot open include file: 'uv.h': No such file or directory
1>Log.cpp
1>C:\Mining\xmrig-nvidia-master\src\log/Log.h(28): fatal error C1083: Cannot open include file: 'uv.h': No such file or directory
1>Client.cpp
1>C:\Mining\xmrig-nvidia-master\src\log/Log.h(28): fatal error C1083: Cannot open include file: 'uv.h': No such file or directory
1>Job.cpp
1>Network.cpp
1>C:\Mining\xmrig-nvidia-master\src\api/Api.h(29): fatal error C1083: Cannot open include file: 'uv.h': No such file or directory
1>DonateStrategy.cpp
1>C:\Mining\xmrig-nvidia-master\src\net/Client.h(29): fatal error C1083: Cannot open include file: 'uv.h': No such file or directory
1>FailoverStrategy.cpp
1>C:\Mining\xmrig-nvidia-master\src\net/Client.h(29): fatal error C1083: Cannot open include file: 'uv.h': No such file or directory
1>SinglePoolStrategy.cpp
1>C:\Mining\xmrig-nvidia-master\src\net/Client.h(29): fatal error C1083: Cannot open include file: 'uv.h': No such file or directory
1>SubmitResult.cpp
1>C:\Mining\xmrig-nvidia-master\src\net\SubmitResult.cpp(25): fatal error C1083: Cannot open include file: 'uv.h': No such file or directory
1>Url.cpp
1>CudaCLI.cpp
1>Options.cpp
1>C:\Mining\xmrig-nvidia-master\src\Options.cpp(26): fatal error C1083: Cannot open include file: 'uv.h': No such file or directory
1>Platform.cpp
1>C:\Mining\xmrig-nvidia-master\src\Platform.cpp(26): fatal error C1083: Cannot open include file: 'uv.h': No such file or directory
1>Generating Code...
1>Compiling...
1>Summary.cpp
1>C:\Mining\xmrig-nvidia-master\src\Summary.cpp(26): fatal error C1083: Cannot open include file: 'uv.h': No such file or directory
1>CudaWorker.cpp
1>C:\Mining\xmrig-nvidia-master\src\workers/Handle.h(29): fatal error C1083: Cannot open include file: 'uv.h': No such file or directory
1>GpuThread.cpp
1>C:\Mining\xmrig-nvidia-master\src\workers\GpuThread.cpp(126): warning C4244: '=': conversion from 'double' to 'int', possible loss of data
1>Handle.cpp
1>C:\Mining\xmrig-nvidia-master\src\workers/Handle.h(29): fatal error C1083: Cannot open include file: 'uv.h': No such file or directory
1>Hashrate.cpp
1>C:\Mining\xmrig-nvidia-master\src\log/Log.h(28): fatal error C1083: Cannot open include file: 'uv.h': No such file or directory
1>Workers.cpp
1>C:\Mining\xmrig-nvidia-master\src\api/Api.h(29): fatal error C1083: Cannot open include file: 'uv.h': No such file or directory
1>xmrig.cpp
1>c:\mining\xmrig-nvidia-master\src\App.h(28): fatal error C1083: Cannot open include file: 'uv.h': No such file or directory
1>App_win.cpp
1>c:\mining\xmrig-nvidia-master\src\App.h(28): fatal error C1083: Cannot open include file: 'uv.h': No such file or directory
1>Cpu_win.cpp
1>Platform_win.cpp
1>C:\Mining\xmrig-nvidia-master\src\Platform_win.cpp(27): fatal error C1083: Cannot open include file: 'uv.h': No such file or directory
1>NvmlApi.cpp
1>C:\Mining\xmrig-nvidia-master\src\nvidia\NvmlApi.cpp(26): fatal error C1083: Cannot open include file: 'uv.h': No such file or directory
1>CryptoNight.cpp
1>Httpd.cpp
1>C:\Mining\xmrig-nvidia-master\src\api\Httpd.cpp(25): fatal error C1083: Cannot open include file: 'microhttpd.h': No such file or directory
1>Generating Code...
1>Done building project "xmrig-nvidia.vcxproj" -- FAILED.
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========

**Comment by metalurgus** [comment]
It looks like you didn't  specify the path to the libraries as for this issue https://github.com/xmrig/xmrig/issues/213

**Comment by rsxdan** [comment]
Does the path have to be specified in the FindUV.cmake file?

**Comment by metalurgus** [comment]
in the `cmake` command
`cmake .. -G "Visual Studio 15 2017 Win64" -T v140,host=x64 -DUV_INCLUDE_DIR="c:\<path>\msvc2015\libuv\x64\include" -DUV_LIBRARY="c:\<path>\msvc2015\libuv\x64\lib\libuv.lib" -DMHD_INCLUDE_DIR="c:\<path>\msvc2015\libmicrohttpd\x64\include" -DMHD_LIBRARY="c:\<path>\msvc2015\libmicrohttpd\x64\lib\libmicrohttpd.lib"` replace <path> with actual path

**Comment by rsxdan** [comment]
Now I get this for compiling, is it ok?:

C:\>cd MinerApp\xmrig-nvidia-master

C:\MinerApp\xmrig-nvidia-master>mkdir build

C:\MinerApp\xmrig-nvidia-master>cd build

C:\MinerApp\xmrig-nvidia-master\build>cmake .. -G "Visual Studio 15 2017 Win64" -T v140,host=x64 -DUV_INCLUDE_DIR="C:\MinerApp\xmrig-deps-2.2\msvc2015\libuv\x64\include" -DUV_LIBRARY="C:\MinerApp\xmrig-deps-2.2\msvc2015\libuv\x64\lib\libuv.lib" -DMHD_INCLUDE_DIR="C:\MinerApp\xmrig-deps-2.2\msvc2015\libmicrohttpd\x64\include" -DMHD_LIBRARY="C:\MinerApp\xmrig-deps-2.2\msvc2015\libmicrohttpd\x64\lib\libmicrohttpd.lib"
-- The C compiler identification is MSVC 19.0.24225.1
-- The CXX compiler identification is MSVC 19.0.24225.1
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found UV: C:/MinerApp/xmrig-deps-2.2/msvc2015/libuv/x64/lib/libuv.lib
-- Found CUDA: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.1 (found suitable version "9.1", minimum required is "7.5")
-- Found NVML: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.1/include
-- Looking for syslog.h
-- Looking for syslog.h - not found
-- Found mhd: C:/MinerApp/xmrig-deps-2.2/msvc2015/libmicrohttpd/x64/include
-- Configuring done
-- Generating done
-- Build files have been written to: C:/MinerApp/xmrig-nvidia-master/build

C:\MinerApp\xmrig-nvidia-master\build>

**Comment by metalurgus** [comment]
this is not an error so far. Try building the solution

**Comment by rsxdan** [comment]
Now I have this, is it good?:

1>------ Build started: Project: ZERO_CHECK, Configuration: Release x64 ------
1>Checking Build System
1>CMake does not need to re-run because C:/MinerApp/xmrig-nvidia-master/build/CMakeFiles/generate.stamp is up-to-date.
2>------ Build started: Project: xmrig-cuda, Configuration: Release x64 ------
2>Building NVCC (Device) object CMakeFiles/xmrig-cuda.dir/src/nvidia/Release/xmrig-cuda_generated_cuda_core.cu.obj
2>cuda_core.cu
2>cuda_core.cu
2>C:/MinerApp/xmrig-nvidia-master/src/nvidia/cuda_core.cu(20): warning C4146: unary minus operator applied to unsigned type, result still unsigned
2>C:/MinerApp/xmrig-nvidia-master/src/nvidia/cuda_core.cu(40): warning C4018: '<': signed/unsigned mismatch
2>Building NVCC (Device) object CMakeFiles/xmrig-cuda.dir/src/nvidia/Release/xmrig-cuda_generated_cuda_extra.cu.obj
2>cuda_extra.cu
2>cuda_extra.cu
2>C:/MinerApp/xmrig-nvidia-master/src/nvidia/cuda_extra.cu(174): warning C4297: 'cryptonight_extra_cpu_set_data': function assumed not to throw an exception but does
2>C:/MinerApp/xmrig-nvidia-master/src/nvidia/cuda_extra.cu(174): note: The function is extern "C" and /EHc was specified
2>C:/MinerApp/xmrig-nvidia-master/src/nvidia/cuda_extra.cu(214): warning C4297: 'cryptonight_extra_cpu_prepare': function assumed not to throw an exception but does
2>C:/MinerApp/xmrig-nvidia-master/src/nvidia/cuda_extra.cu(214): note: The function is extern "C" and /EHc was specified
2>C:/MinerApp/xmrig-nvidia-master/src/nvidia/cuda_extra.cu(242): warning C4018: '<': signed/unsigned mismatch
2>C:/MinerApp/xmrig-nvidia-master/src/nvidia/cuda_extra.cu(226): warning C4297: 'cryptonight_extra_cpu_final': function assumed not to throw an exception but does
2>C:/MinerApp/xmrig-nvidia-master/src/nvidia/cuda_extra.cu(226): note: The function is extern "C" and /EHc was specified
2>C:/MinerApp/xmrig-nvidia-master/src/nvidia/cuda_extra.cu(227): warning C4297: 'cryptonight_extra_cpu_final': function assumed not to throw an exception but does
2>C:/MinerApp/xmrig-nvidia-master/src/nvidia/cuda_extra.cu(227): note: The function is extern "C" and /EHc was specified
2>C:/MinerApp/xmrig-nvidia-master/src/nvidia/cuda_extra.cu(229): warning C4297: 'cryptonight_extra_cpu_final': function assumed not to throw an exception but does
2>C:/MinerApp/xmrig-nvidia-master/src/nvidia/cuda_extra.cu(229): note: The function is extern "C" and /EHc was specified
2>C:/MinerApp/xmrig-nvidia-master/src/nvidia/cuda_extra.cu(231): warning C4297: 'cryptonight_extra_cpu_final': function assumed not to throw an exception but does
2>C:/MinerApp/xmrig-nvidia-master/src/nvidia/cuda_extra.cu(231): note: The function is extern "C" and /EHc was specified
2>C:/MinerApp/xmrig-nvidia-master/src/nvidia/cuda_extra.cu(232): warning C4297: 'cryptonight_extra_cpu_final': function assumed not to throw an exception but does
2>C:/MinerApp/xmrig-nvidia-master/src/nvidia/cuda_extra.cu(232): note: The function is extern "C" and /EHc was specified
2>C:/MinerApp/xmrig-nvidia-master/src/nvidia/cuda_extra.cu(360): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data
2>C:/MinerApp/xmrig-nvidia-master/src/nvidia/cuda_extra.cu(349): warning C4297: 'cuda_get_deviceinfo': function assumed not to throw an exception but does
2>C:/MinerApp/xmrig-nvidia-master/src/nvidia/cuda_extra.cu(349): note: The function is extern "C" and /EHc was specified
2>Building Custom Rule C:/MinerApp/xmrig-nvidia-master/CMakeLists.txt
2>CMake is re-running because C:/MinerApp/xmrig-nvidia-master/build/CMakeFiles/generate.stamp is out-of-date.
2>  the file 'C:/MinerApp/xmrig-nvidia-master/build/CMakeFiles/xmrig-cuda.dir/src/nvidia/xmrig-cuda_generated_cuda_core.cu.obj.depend'
2>  is newer than 'C:/MinerApp/xmrig-nvidia-master/build/CMakeFiles/generate.stamp.depend'
2>  result='-1'
2>-- Configuring done
2>-- Generating done
2>-- Build files have been written to: C:/MinerApp/xmrig-nvidia-master/build
2>xmrig-cuda.vcxproj -> C:\MinerApp\xmrig-nvidia-master\build\Release\xmrig-cuda.lib
2>Done building project "xmrig-cuda.vcxproj".
3>------ Build started: Project: xmrig-nvidia, Configuration: Release x64 ------
3>Building Custom Rule C:/MinerApp/xmrig-nvidia-master/CMakeLists.txt
3>CMake does not need to re-run because C:/MinerApp/xmrig-nvidia-master/build/CMakeFiles/generate.stamp is up-to-date.
3>Api.cpp
3>ApiState.cpp
3>NetworkState.cpp
3>C:\MinerApp\xmrig-nvidia-master\src\api\NetworkState.cpp(48): warning C4244: 'return': conversion from 'uint64_t' to 'int', possible loss of data
3>C:\MinerApp\xmrig-nvidia-master\src\api\NetworkState.cpp(58): warning C4267: 'return': conversion from 'size_t' to 'uint32_t', possible loss of data
3>App.cpp
3>Console.cpp
3>Cpu_stub.cpp
3>ConsoleLog.cpp
3>FileLog.cpp
3>Log.cpp
3>Client.cpp
3>C:\MinerApp\xmrig-nvidia-master\src\net\Client.cpp(535): warning C4267: '=': conversion from 'size_t' to 'ULONG', possible loss of data
3>Job.cpp
3>Network.cpp
3>DonateStrategy.cpp
3>FailoverStrategy.cpp
3>SinglePoolStrategy.cpp
3>SubmitResult.cpp
3>Url.cpp
3>CudaCLI.cpp
3>Options.cpp
3>Platform.cpp
3>Generating Code...
3>Compiling...
3>Summary.cpp
3>CudaWorker.cpp
3>GpuThread.cpp
3>C:\MinerApp\xmrig-nvidia-master\src\workers\GpuThread.cpp(126): warning C4244: '=': conversion from 'double' to 'int', possible loss of data
3>Handle.cpp
3>Hashrate.cpp
3>Workers.cpp
3>xmrig.cpp
3>App_win.cpp
3>Cpu_win.cpp
3>Platform_win.cpp
3>NvmlApi.cpp
3>CryptoNight.cpp
3>Httpd.cpp
3>Generating Code...
3>c_keccak.c
3>c_groestl.c
3>c_blake256.c
3>c_jh.c
3>c_skein.c
3>soft_aes.c
3>Generating Code...
3>libuv.lib(thread.obj) : MSIL .netmodule or module compiled with /GL found; restarting link with /LTCG; add /LTCG to the link command line to improve linker performance
3>   Creating library C:/MinerApp/xmrig-nvidia-master/build/Release/xmrig-nvidia.lib and object C:/MinerApp/xmrig-nvidia-master/build/Release/xmrig-nvidia.exp
3>Generating code
3>Finished generating code
3>xmrig-nvidia.vcxproj -> C:\MinerApp\xmrig-nvidia-master\build\Release\xmrig-nvidia.exe
3>Done building project "xmrig-nvidia.vcxproj".
4>------ Skipped Build: Project: ALL_BUILD, Configuration: Release x64 ------
4>Project not selected to build for this solution configuration 
========== Build: 3 succeeded, 0 failed, 0 up-to-date, 1 skipped ==========

**Comment by rsxdan** [comment]
If I try to run the app in the Release folder, it closes right away.

**Comment by metalurgus** [comment]
`Build: 3 succeeded, 0 failed` is self-explaining.  `If I try to run the app in the Release folder, it closes right away.`  - that's probably because you don't provide it with any config or command line arguments. See [Usage](https://github.com/xmrig/xmrig-nvidia#usage)

**Comment by rsxdan** [comment]
Good I setup the config file but where do I input the command line? Sorry I'm new to this :(

**Comment by rsxdan** [comment]
This is what is happening:

![xmrig](https://user-images.githubusercontent.com/36334505/36067661-63484140-0e8f-11e8-8441-bf44ccf2f34b.jpg)

**Comment by metalurgus** [comment]
You don't need it to run in Nvidia <something> console.

1. place your config file in the same dir as `xmrig-nvidia.exe`

**Comment by metalurgus** [comment]
BTW why at all do you want to compile it by yourself? Why not to just download prebuilt binaries?

**Comment by rsxdan** [comment]
Good thanks a lot for your help.
