### ISSUE TITLE
CMake lists

### ISSUE THREAD

**Issue by nmr2** [xmrig/xmrig-nvidia#109]
Hello,

I tried to execute the command:

cmake .. -G "Visual Studio 15 2017 Win64" -T v140,host=x64 -DUV_INCLUDE_DIR="c                                                        :\<path>\msvc2015\libuv\x64\include" -DUV_LIBRARY="c:\<path>\msvc2015\libuv\x64\                                                        lib\libuv.lib" -DMHD_INCLUDE_DIR="c:\<path>\msvc2015\libmicrohttpd\x64\include"                                                         -DMHD_LIBRARY="c:\<path>\msvc2015\libmicrohttpd\x64\lib\libmicrohttpd.lib"

However I received the following error

CMake Error: The source directory "/xmrig-nvidia-master" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.

**Comment by xmrig** [comment]
You need create directory `build` (name not important) and run cmake inside or replace `..` to `.`. Also you need replace `<path>` to actual path.
Thank you.

**Comment by nmr2** [comment]
Thank you for your reply.

Sorry, I really don't know how to program, I am at a very basic level.
Could you pleas explain in more detail what I need to do?

I tried to run the program in two ways:

C:\xmr-stak-dep\xmr-stak-2.2.0\build>cmake --build . --config Release
--target install
Microsoft(R) Build Engine versão 15.5.180.51428 para .NET Framework
Copyright (C) Microsoft Corporation. Todos os direitos reservados.

Compilação de 18/02/2018 21:18:54 iniciada.
Projeto "C:\xmr-stak-dep\xmr-stak-2.2.0\build\install.vcxproj" no nó 1
(destinos padrão).
O projeto "C:\xmr-stak-dep\xmr-stak-2.2.0\build\install.vcxproj" (1) está
compilando "C:\xmr-stak-dep\xmr-stak-2.2.0\build\ZERO_CHECK.vcxproj" (2) no
nó 1 (destinos padrão).
InitializeBuildStatus:
  Tocando "x64\Release\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild".
CustomBuild:
  Checking Build System
  CMake does not need to re-run because
C:/xmr-stak-dep/xmr-stak-2.2.0/build/CMakeFiles/generate.stamp is
up-to-date.

--------------

Also on CMAKE

[image: Inline image 1]
[image: Inline image 2]


Also didn't understand the instruction to change the path

Thank you,

Fred

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Livre
de vírus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>.
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by metalurgus** [comment]
But why do you need to build it at all? Why not just use prebuilt binaries?
