### ISSUE TITLE
Unable to set block size/thread via command args

### ISSUE THREAD

**Issue by calvintam236** [xmrig/xmrig-nvidia#11]
I have run `xmr-stak-nvidia`, and it gives me around 100H/s using this config: `"threads" : 46, "blocks" : 4, "bfactor" : 12, "bsleep" :  0`.
Just build the `xmrig-nvidia` on macOS, and with auto gpu config on `GeForce GT 750M @ 925/2508 MHz`, I could only get around 60H/s with it gets around 16 threads..
I couldn't find an option to set block size/thread via command args. Anything you can help improve this result?

**Comment by xmrig** [comment]
GPU options can changed only config file, place config.json near xmrig executable, it will update config and you can change options.
Thank you.

**Comment by calvintam236** [comment]
Can you add such command args if I use just one GPU to mine? (I don't want to setup json file because it is more complicated to edit it in docker...)

**Comment by xmrig** [comment]
@calvintam236 Can you suggest how command line options should named and how it use with multiple GPUs. Thank you.

**Comment by calvintam236** [comment]
As the miner is going to merge CPU, AMD, and Nvidia versions in the future, I would suggest to add prefix to command args now. For Nvidia version, you can use `--cuda`.
For multiple GPUs setup, how about `--cuda-threads 1000,2000 --cuda-blocks 1000,2000`,  which 1000 for gpu index 0, 2000 for gpu index 1. Same changes needed for `--bfactor` and `--bsleep`.
`--max-gpu-threads` will be replaced by the new thread option?

**Comment by xmrig** [comment]
I added new options:

* `--cuda-devices` List of CUDA devices to use, optional, if not specified all available devices will be used. Examples: `--cuda-devices=0`, `--cuda-devices=0,2`, etc.
* `--cuda-launch=THREADSxBLOCKS` Single option to specify threads and blocks, also can be comma separated. Other miners like ccminer and xmrMiner uses a launch option too.
* `--bfactor`, `--bsleep` not renamed, no equivalent for AMD, can be comma separated now.
* `--max-gpu-threads` deprecated, added `--cuda-max-threads` with equal functionality.

**Comment by calvintam236** [comment]
@xmrig Thank you for the update and great work.

While `--bfactor` and `--bsleep` don't have equivalent for AMD, no `cuda` prefix will make user think that these options are available for AMD as well.

**Comment by calvintam236** [comment]
Great job 👍  Now it's better

**Comment by markusikul** [comment]
http://joxi.ru/J2bbBYnt41EP92
what memory is missing?
