### ISSUE TITLE
no payout ???

### ISSUE THREAD

**Issue by volzak** [xmrig/xmrig-nvidia#111]
I am wondering why after 24 hours of gpu mining on gtx1080ti i have no payout at all . I have done the config json with my wallet address . Is it possible that it require a integrated address ? other wise i am out of clue about why i have no payout, not even a percentile of a fraction of ...

{
    "algo": "cryptonight",
    "background": false,
    "colors": true,
    "donate-level": 1,
    "log-file": null,
    "print-time": 60,
    "retries": 5,
    "retry-pause": 5,
    "threads": [
        {
            "index": 0,
            "threads": 44,
            "blocks": 27,
            "bfactor": 6,
            "bsleep": 25,
            "affine_to_cpu": false
        }
    ],
    "pools": [
        {
            "url": "monerohash.com:5555",
            "user": "**************",
            "pass": "x",
            "keepalive": true,
            "nicehash": false
        }
    ],
    "api": {
        "port": 8080,
        "access-token": null,
        "worker-id": null
    }
}

**Comment by tudde** [comment]
This has nothing to do with miner itself but with pool. 
https://monerohash.com/#getting_started
> When mining to a standard address the minimum payout is 0.5 XMR.

So be patient, it's gonna take quite long. :)

**Comment by volzak** [comment]
thx
