### ISSUE TITLE
whats the minimum cuda capability  for this ?

### ISSUE THREAD

**Issue by y1111** [xmrig/xmrig-nvidia#113]
will it work on cuda 1.2 cards ?

**Comment by tudde** [comment]
It seems that binaries don't support cuda arch below 2.0. Cuda 9 starts at 3.0.

**Comment by y1111** [comment]
is there how to adapt it to run on older cards ? cuda 1.1 and 1.2 with cuda 6.5 
what binaries or libraries would need to be changed ?

**Comment by tudde** [comment]
Without really knowing much about the code I guess it would be possible, but I don't think it would be worth the effort though. Video cards of compute capability 1.2 don't have that many cores and their core and memory clocks are lower, also their computing power per watt is considerably lower making mining painfully slow and unprofitable.
