### ISSUE TITLE
Virus alerte V2.4.5

### ISSUE THREAD

**Issue by Fungraphic** [xmrig/xmrig-nvidia#114]
Avast virus alerte on v2.4.5
![2018-02-21_220321](https://user-images.githubusercontent.com/26345101/36505226-2077ca80-1753-11e8-8c89-89913fe1c0ee.jpg)

**Comment by xmrig** [comment]
You can add the miner to exclusion list. Actually can't do anything with detection. Please read https://github.com/xmrig/xmrig/issues/270#issuecomment-352305211
Thank you.

**Comment by Fungraphic** [comment]
![pouce](https://user-images.githubusercontent.com/26345101/36618277-d270d964-18ea-11e8-9938-f2d31ffb2ed3.png)
![superthumb](https://user-images.githubusercontent.com/26345101/36618279-d4f978c6-18ea-11e8-92ba-fa72e7e41cfb.jpg)
