### ISSUE TITLE
BUILD ERROR SOMEONE HELP!!!!!

### ISSUE THREAD

**Issue by n0file** [xmrig/xmrig-nvidia#116]
![image](https://user-images.githubusercontent.com/36566127/36580687-56488c58-187a-11e8-94f5-c26c81173323.png)
CMake worked just fine but that error really sucks in VS2015 and VS2017 too

HELP HELP HELP HELP HELP

**Comment by xmrig** [comment]
If you use `-G "Visual Studio 15 2017 Win64"` you should choice msvc2015 libs.
Thank you.

**Comment by n0file** [comment]
@xmrig you dont even realise how much i love you
