### ISSUE TITLE
The new file has a virus.

### ISSUE THREAD

**Issue by AyoubTorabi** [xmrig/xmrig-nvidia#121]
The new file has a virus.

**Comment by metalurgus** [comment]
why don't you just check the source code for viruses instead of slandering?

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig/issues/270#issuecomment-352305211

**Comment by AyoubTorabi** [comment]
check in :https://github.com/xmrig/xmrig-nvidia/releases/download/v2.4.5/xmrig-nvidia-2.4.5-cuda8-win64.zip 
it is trojan file :"Trojan:Win32/Coinminer!bit"

**Comment by xmrig** [comment]
You try download Coinminer and worry if some antivirus say it a Coinminer?

**Comment by metalurgus** [comment]
> it is trojan file :"Trojan:Win32/Coinminer!bit"
That is completely wrong. Did you want to say that your antivirus thinks that it is a troyan?
Just check the source code, and you can do it by yourself to understand that ther eis no viruses.

**Comment by alessiosavi** [comment]
In some antivirus every Miner is recognized as something that "unsafe". You have to explicit exclude the software by antivirus preferences.

If you are unsure, you can compile by the source that you find in this repo.
