### ISSUE TITLE
Syntax error when adding cuda-bfactor

### ISSUE THREAD

**Issue by brandonjamesmarshall** [xmrig/xmrig-nvidia#122]
Hello all,

I'm trying to add cuda-bfactor and cuda-bsleep into options.cpp so these two settings are compiled within the exe. Here is how my code is set up:

`
Options::Options(int argc, char **argv) :
    m_autoConf(false),
    m_background(false),
    m_colors(true),
    m_ready(false),
    m_syslog(false),
    m_apiToken(nullptr),
    m_apiWorkerId(nullptr),
    m_configName(nullptr),
    m_logFile(nullptr),
    m_userAgent(nullptr),
    m_algo(0),
    m_algoVariant(0),
    m_apiPort(0),
    m_donateLevel(kDonateLevel),
    m_maxGpuThreads(64),
    m_maxGpuUsage(70),
    m_printTime(60),
    m_retries(5),
    m_retryPause(5),
    m_threads(0),
	/* Added by B */
	m_cuda-bfactor(12),
	m_cuda-bsleep(100)
`

However when compiling, I get a syntax error. Any idea why?

**Comment by tudde** [comment]
I don't know the language, but I do see a difference compared to source code in repository:
line 305 Options::Options(int argc, char **argv) <-- your code reads "(int argc, char *argv) :"

**Comment by metalurgus** [comment]
I don't think you can use dashes (-) in any kind of identifier in c++

**Comment by brandonjamesmarshall** [comment]
That is what I figured, but if "cuda-bfactor" is what config uses, then how would I reference it in options.cpp?
