### ISSUE TITLE
Fatal error when building ALL_BUILD in Visual Studio

### ISSUE THREAD

**Issue by brandonjamesmarshall** [xmrig/xmrig-nvidia#124]
I'm currently having some trouble compiling on the latest version. I've been able to compile xmrig (cpu version) with no issues. I've tried using both master and dev versions of xmrig-deps as well. But the nvidia version is giving me a fatal error in Visual Studio.

Here is the Cmake log:
> cmake .. -G "Visual Studio 15 2017 Win64" -T v140,host=x64 -DUV_INCLUDE_DIR="D:\_Brandon\OneDrive\Documents\GitHub\xmrig-deps\msvc2017\x64\include" -DUV_LIBRARY="D:\_Brandon\OneDrive\Documents\GitHub\xmrig-deps\msvc2017\x64\lib\libuv.lib" -DMHD_INCLUDE_DIR="D:\_Brandon\OneDrive\Documents\GitHub\xmrig-deps\msvc2017\x64\include" -DMHD_LIBRARY="D:\_Brandon\OneDrive\Documents\GitHub\xmrig-deps\msvc2017\x64\lib\libmicrohttpd.lib"
> -- The C compiler identification is MSVC 19.0.24231.0
> -- The CXX compiler identification is MSVC 19.0.24231.0
> -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe
> -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe
> -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Found UV: D:/_Brandon/OneDrive/Documents/GitHub/xmrig-deps/msvc2017/x64/lib/libuv.lib
> -- Found CUDA: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.1 (found suitable version "9.1", minimum required is "7.5")
> -- Found NVML: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.1/include
> -- Looking for syslog.h
> -- Looking for syslog.h - not found
> -- Found mhd: D:/_Brandon/OneDrive/Documents/GitHub/xmrig-deps/msvc2017/x64/include
> -- Configuring done
> -- Generating done
> -- Build files have been written to: D:/_Brandon/OneDrive/Documents/GitHub/xmrig-nvidia/build

When opening the .sln file in Visual Studio and choosing to build "ALL_BUILD", it gets halfway through then throws up the following error:

> The project "ALL_BUILD" has been modified outside the environment.

Whether I click Reload or Ignore, the build then fails with these two errors:

> Severity	Code	Description	Project	File	Line	Suppression State
> Error	C1900	Il mismatch between 'P1' version '20161212' and 'P2' version '20150812'	xmrig-nvidia	D:\_Brandon\OneDrive\Documents\GitHub\xmrig-nvidia\build\LINK	1	

> Severity	Code	Description	Project	File	Line	Suppression State
> Error	LNK1257	code generation failed	xmrig-nvidia	D:\_Brandon\OneDrive\Documents\GitHub\xmrig-nvidia\build\LINK	1	

Any assistance would be appreciated! I was able to build xmrig just fine, but otherwise I'm pretty new to compiling/building things on my own.

**Comment by irobot335** [comment]
Exact same issue, i had used the same commands a few months earlier to build a version for myself and it worked perfectly. After performing a pull from this repository I am also unable to build In Visual Studio given the same error.

`3>Generating Code...
3>libuv.lib(thread.obj) : MSIL .netmodule or module compiled with /GL found; restarting link with /LTCG; add /LTCG to the link command line to improve linker performance
3>LINK : fatal error C1900: Il mismatch between 'P1' version '20161212' and 'P2' version '20150812'
3>LINK : fatal error LNK1257: code generation failed
3>Done building project "xmrig-nvidia.vcxproj" -- FAILED.
4>------ Rebuild All started: Project: ALL_BUILD, Configuration: Release x64 ------`

Creating the build folder with the solution file is all done perfectly well. I am using CUDA 8.0 and have tried with CUDA 9.0 to no avail, trying both the '-T v140,host=x64' and '-T v141,host=x64' flags. Thanks for any help

**Comment by xmrig** [comment]
With `-T v140,host=x64` you should use msvc2015 libs (not msvc2017). You can use precompiled dependencies (if not use already) https://github.com/xmrig/xmrig-deps
Thank you.

**Comment by brandonjamesmarshall** [comment]
This seems to fix the error and the .exe is built successfully. Thank you @xmrig for the support and a fantastic piece of software!

I do still receive this error after build, but I guess I'll ignore it:
> The project "ALL_BUILD" has been modified outside the environment.

**Comment by douirc** [comment]
> With -T v140,host=x64 you should use msvc2015 libs (not msvc2017).

yes, this worked for me!  in what scenario do you use msvc2017?

cmake .. -G "Visual Studio 15 2017 Win64" -T v140,host=x64 -DXMRIG_DEPS=C:\Users\jacko\Downloads\xmrig-deps-3.0\msvc2015\x64 -DWITH_HTTPD=OFF -DUV_LIBRARY=C:\Users\jacko\Downloads\xmrig-deps-3.0\msvc2015\x64\lib\libuv.lib -DMHD_LIBRARY=C:\Users\jacko\Downloads\xmrig-deps-3.0\msvc2015\x64\lib\libmicrohttpd.lib -DUV_INCLUDE_DIR=C:\Users\jacko\Downloads\xmrig-deps-3.0\msvc2015\x64\include
