### ISSUE TITLE
Command args - only run on specified GPUs

### ISSUE THREAD

**Issue by calvintam236** [xmrig/xmrig-nvidia#13]
It seems there is no way to assign which GPU(s) to be used for each process. It should support to run only on specific CUDA device by command args, e.g. `--cuda-devices 0 1`.

**Comment by rs2pt** [comment]
Hi. I am just not using xmrig because I can't assign GPU. :-/
but I love it

**Comment by xmrig** [comment]
It supported, but now only via config file, place `config.json` file near executable of specify path to file via command line option `-c`, on first run config will updated, with initial auto configuration options (may not best) then you can change anything. Thank you,

**Comment by rs2pt** [comment]
cool thanks :-)

**Comment by calvintam236** [comment]
Please add support via command args. Other miners, e.g. `ethminer`, all have this option.

**Comment by rs2pt** [comment]
Hi calvintam236, I found it quite easy and helps to keep the command line args a bit cleaner. :-)

**Comment by calvintam236** [comment]
However, I am running it on Docker. Editing/Deploying with a file in the docker container is not as easy and friendly as you think.

**Comment by rs2pt** [comment]
true :-/

**Comment by xmrig** [comment]
Merge with #11
