### ISSUE TITLE
Support for cryptonight-heavy

### ISSUE THREAD

**Issue by felipe-vvoosh** [xmrig/xmrig-nvidia#144]
Hi, when are you guys going to support it?

Thanks

**Comment by xmrig** [comment]
Yep, use `"algo": "cryptonight-heavy",` in config.
https://github.com/xmrig/xmrig-nvidia/releases/tag/v2.6.0-beta1
Thank you.

**Comment by felipe-vvoosh** [comment]
Thanks @xmrig!
