### ISSUE TITLE
Issue with Code Analysis VS17

### ISSUE THREAD

**Issue by jd94** [xmrig/xmrig-nvidia#146]
Hello, I'm getting this issue when I load the CMakeLists.txt, I'm not able to have the build folder with the .sln because of this, first time I'm seeing this. Thanks in advance, didn't have this issue with xmrig cpu version.

Severity	Code	Description	Project	File	Line	Suppression State
Error		
CMake Error at C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find UV (missing: UV_LIBRARY UV_INCLUDE_DIR)		

C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake	137

**Comment by xmrig** [comment]
Please read the docs https://github.com/xmrig/xmrig-nvidia/wiki/Windows-Build#compile looks like you don't add `-DXMRIG_DEPS=<path>`.
Thank you.

**Comment by jd94** [comment]
xmrig, thank you for the crazy fast reply. What deps exactly do I use, are the 3.0 version ones fine I found from xmrig cpu? Thanks!

**Comment by jd94** [comment]
I've figured out the rest myself. Thank you xmrig!
