### ISSUE TITLE
Almost completely locks up computer, gets a puny 150H/s

### ISSUE THREAD

**Issue by dinicthis** [xmrig/xmrig-nvidia#15]
Why does this suck so mega-harshly? It runs, with the parameters as set for mining pool, etc, and shows up as the slow, lame, worthless miner that it is on my pool stats.

My CPU does better than this.

How about if you take some of the viruses and trojans out of it so it will actually MINE?

Strangely, I get ccminer to work fine at 550 or so H/s

**Comment by calvintam236** [comment]
What GPU are you using?

**Comment by dinicthis** [comment]
980

**Comment by dinicthis** [comment]
Oh, and CCminer doesn't get immediately deleted by Windows Defender, but xmrig does. Considering the fact that it is almost locking the computer, I think it's safe to say it looks like it has malware in it.

**Comment by calvintam236** [comment]
As I know, a lot of miners got deleted by antivirus. This miner is open-source, so you can take a look on the source code.

I know that the auto config doesn't do the best performance (my personal experience), so are you using `config.json` to set the threads and blocks for the GPU?

**Comment by dinicthis** [comment]
everything I tried didn't get any results that werebetter. and why would it
lag out my system?

ccminer doesn't do that.

**Comment by calvintam236** [comment]
I believe you didn't set bfactor to 12 avoid lag. Do you mind sharing what parameters you tried?

**Comment by dinicthis** [comment]
why? can it do better tban ccminer?


Sent from my Samsung device

-------- Original message --------

**Comment by xmrig** [comment]
ccminer use by default bfactor 11 (max value 12) and bsleep 100, xmrig and also in xmr-stak-nvidia use bfactor 6 and bsleep 25 it better for performance, but worse if want use GPU for surf your desktop.

**Comment by dinicthis** [comment]
Except it gets half the hashrate of ccminer, so that means it is not better for performance.

**Comment by xmrig** [comment]
There no any positive way to get half hashrate with equal settings.
