### ISSUE TITLE
Could not find NVML

### ISSUE THREAD

**Issue by paulmadore** [xmrig/xmrig-nvidia#16]
Hi, 

I'm excited to try this out. Unfortunately when building on a freshly installed Xubuntu 16.04, I get the error that it cannot find NVML. I've verified that libnvidia-ml.so etc are in the cuda directory, and it's able to find Cuda after I specify where Cuda is. I tried specifying the flag it asks for (NVML_SOURCE_DIR or whatever it is -- the output is on another computer), but it doesn't seem to mean anything to Cmake.

**Comment by xmrig** [comment]
For build required only header file `nvml.h` you can specify directory where file located via `-DNVML_INCLUDE_DIR=/path/to/include`

Library named `libnvidia-ml.so` manually loaded in runtime, in compile time this library not required.
Thank you.

**Comment by paulmadore** [comment]
Okay, that seems to be working. For me it was in /usr/include/hwloc (used apt-file to find it).

**Comment by Hiyorimi** [comment]
I think it might be useful to add this information to the [wiki](https://github.com/xmrig/xmrig-nvidia/wiki/Ubuntu-Build).
