### ISSUE TITLE
Threads and Blocks for nVidia GTX 10 series

### ISSUE THREAD

**Issue by GrannyCryptomaster** [xmrig/xmrig-nvidia#166]
These are the Threads and Blocks settings for GTX 10 series in Windows, by my calculations.
I used SMXx4 for Blocks; it seems the best value; Threads should be used no more than 32; 
Ideal TxB = No. of cores; memory needed = TxBx1 (CNL) or TxBx2 (CN) or TxBx4 (CNH); 
CN Lite uses 1MB/thread; CN uses 2MB/thread; CN Heavy uses 4MB/thread.
For CN Lite you can use the same settings as CN or double the Blocks to see whitch hashes better.
Windows reserves aprox 21% video memory on all cards in the rig, so your available video memory is smaller than installed video memory. I don't know the exact amount available in Windows for each model; if you add it in the comments, I will update my calculations. I have only GTX 1060 3GB cards.
It seems that:
-the most eficient by utilised cores for CNHeavy is 1050 Ti 4GB;
-the least eficient is 1060 3GB.

**GTX Model | Memory | Cores | SMX | Blocks | CN Threads | CNH Threads Linux | CNH Threads Win**

Titan Xp | 12 | 3840 | 30 | 120 | 32 | 25 | 20
Titan X | 12 | 3584 | 28 | 112 | 32 | 27 | 21
1080 Ti | 11 | 3584 | 28 | 112 | 32 | 25 | 19
1080 | 8 | 2560 | 20 | 80 | 32 | 25 | 20
1070 Ti | 8 | 2432 | 19 | 76 | 32 | 26 | 21
1070 laptop | 8 | 2048 | 16 | 64 | 32 | 32 | 25
1070 | 8 | 1920 | 15 | 60 | 32 | 32 | 27
1060 | 6 | 1280 | 10 | 40 | 32 | 32 | 30
1060 | 3 | 1152 | 9 | 36 | 32 | 21 | 16
1050 Ti | 4 | 768 | 6 | 24 | 32 | 32 | 32
1050 | 2 | 640 | 5 | 20 | 32 | 25 | 20
1050 laptop | 4 | 640 | 5 | 20 | 32 | 32 | 32
1030 | 2 | 384 | 3 | 12 | 32 | 32 | 32

**Comment by GrannyCryptomaster** [comment]
Updated

**Comment by GrannyCryptomaster** [comment]
Please tell me the exact available video memory in Windows 10 x64 for each GTX model.
It is shown by some miners... I don't remember wich... EWBF's Zcash or XMRig.
Thanks!

**Comment by username1565** [comment]
Looking for best parameters for algorithm `cryptonight-turtle/cn-pico`,
and for GTX 1080Ti.
Interesting the following parameters in config: `cuda-max-threads`, and also `threads`, `blocks`, `bfactor`, `bsleep`.
Or by the output of `xmrig-nvidia.exe --help`, the following parameters:
```
--cuda-max-threads=N  limit maximum count of GPU threads in automatic mode
--cuda-launch=TxB     list of launch config for the CryptoNight kernel
--cuda-bfactor=[0-12] run CryptoNight core kernel in smaller pieces
--cuda-bsleep=N       insert a delay of N microseconds between kernel launches
```
https://www.geforce.com/hardware/desktop-gpus/geforce-gtx-1080-ti/specifications
https://gist.githubusercontent.com/nelson-liu/623eb54d977c98db005eaf2fbc449238/raw/8e6c4d1ad0beecf068d790a7118bf5e0f7baeb91/1080_ti_cuda_8.0_devicequery_output.txt


As I understand, from this line:
```
Ideal TxB = No. of cores;
```
`TxB` this means `Threads` x `Blocks`, and this must to be equal of `3584 CUDA Cores`.
And from this line:
```
GTX Model 	| Memory	| Cores	| SMX	| Blocks 	| CN Threads 	| CNH Threads Linux	| CNH Threads Win
1080 Ti 	| 11		| 3584	| 28	| 112 		| 32 		| 25 			| 19
```
I see `CN Threads` x `Blocks` = `32 * 112` = `3584` = `3584 CUDA Cores` for `GTX 1080Ti`.
So, `max-cuda-threads` should to be = `32`, right? This is a `Warp size: 32`, from `1080Ti`-specifications?
But what about `bfactor` and `bsleep`?
Also, where `SMX`-value can be changed?
And how much memory eating the `cryptonight-turtle(cn-pico)` algo?
As I understand, from this line:
```
memory needed = TxBx1 (CNL) or TxBx2 (CN) or TxBx4 (CNH);
```
this is `Threads x Blocks x Memory`, where `Memory` value - this is a constant for each algo?
