### ISSUE TITLE
Does xmrig-nvidia support arm architecture ?

### ISSUE THREAD

**Issue by laudai** [xmrig/xmrig-nvidia#167]
Hi I'm new to xmrig-nvidia and c compiler
I try to compiler xmrig-nvidia on Jetson TX1
but get fatal error
`/home/ubuntu/xmrig-nvidia/src/3rdparty/rapidjson/reader.h:35:23: fatal error: emmintrin.h: No such file or directory
` 
Does xmrig-nvidia support arm architecture likes xmrig ?
Thank you .

**Comment by xmrig** [comment]
ARM not supported, CPU part can be adapted, but I don't sure about CUDA.
Thank you.
