### ISSUE TITLE
Information on GPU isn't correctly displayed

### ISSUE THREAD

**Issue by zvsoft** [xmrig/xmrig-nvidia#17]
![error xmrig](https://user-images.githubusercontent.com/8188691/30761072-261f7488-a007-11e7-9837-dbe6bfb28a11.jpg)

**Comment by xmrig** [comment]
Oh thank you found another bug, one is already fixed in dev branch https://github.com/xmrig/xmrig-nvidia/commit/d77183cbc1016d7ecbdecf160ba4ef47d732e8bc CUDA GPU 0 is not always GPU 0 in NVML API used for monitoring, but it not your case.

**Comment by xmrig** [comment]
Clocks and power information not available for GTS 450. I fixed bug for this GPU will be only displayed temperature and fan speed.
