### ISSUE TITLE
Segmentation Fault on console hashrate display

### ISSUE THREAD

**Issue by dirtydavemcgee** [xmrig/xmrig-nvidia#172]
Just like it sounds. Miner will start and run until the hashrate is displayed in console, API hashrate is correct.
Debian 9

**Comment by dirtydavemcgee** [comment]
cmake output

user@main:~/xmrig-nvidia/build$ cmake ..
-- The C compiler identification is GNU 6.3.0
-- The CXX compiler identification is GNU 6.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found UV: /usr/lib/x86_64-linux-gnu/libuv.a  
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr/local/cuda (found suitable version "9.1", minimum required is "7.5") 
-- Found NVML: /usr/local/cuda/include  
-- Looking for syslog.h
-- Looking for syslog.h - found
-- Found MHD: /usr/lib/x86_64-linux-gnu/libmicrohttpd.so  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/user/xmrig-nvidia/build

**Comment by dirtydavemcgee** [comment]
make output

user@main:~/xmrig-nvidia/build$ make
[  2%] Building NVCC (Device) object CMakeFiles/xmrig-cuda.dir/src/nvidia/xmrig-cuda_generated_cuda_extra.cu.o
[  4%] Building NVCC (Device) object CMakeFiles/xmrig-cuda.dir/src/nvidia/xmrig-cuda_generated_cuda_core.cu.o
Scanning dependencies of target xmrig-cuda
[  6%] Linking CXX static library libxmrig-cuda.a
[  6%] Built target xmrig-cuda
Scanning dependencies of target xmrig-nvidia
[  9%] Building CXX object CMakeFiles/xmrig-nvidia.dir/src/api/Api.cpp.o
[ 11%] Building CXX object CMakeFiles/xmrig-nvidia.dir/src/api/ApiState.cpp.o
[ 13%] Building CXX object CMakeFiles/xmrig-nvidia.dir/src/api/NetworkState.cpp.o
[ 16%] Building CXX object CMakeFiles/xmrig-nvidia.dir/src/App.cpp.o
[ 18%] Building CXX object CMakeFiles/xmrig-nvidia.dir/src/Console.cpp.o
[ 20%] Building CXX object CMakeFiles/xmrig-nvidia.dir/src/Cpu_stub.cpp.o
[ 23%] Building CXX object CMakeFiles/xmrig-nvidia.dir/src/log/ConsoleLog.cpp.o
[ 25%] Building CXX object CMakeFiles/xmrig-nvidia.dir/src/log/FileLog.cpp.o
[ 27%] Building CXX object CMakeFiles/xmrig-nvidia.dir/src/log/Log.cpp.o
[ 30%] Building CXX object CMakeFiles/xmrig-nvidia.dir/src/net/Client.cpp.o
[ 32%] Building CXX object CMakeFiles/xmrig-nvidia.dir/src/net/Job.cpp.o
[ 34%] Building CXX object CMakeFiles/xmrig-nvidia.dir/src/net/Network.cpp.o
[ 37%] Building CXX object CMakeFiles/xmrig-nvidia.dir/src/net/strategies/DonateStrategy.cpp.o
[ 39%] Building CXX object CMakeFiles/xmrig-nvidia.dir/src/net/strategies/FailoverStrategy.cpp.o
[ 41%] Building CXX object CMakeFiles/xmrig-nvidia.dir/src/net/strategies/SinglePoolStrategy.cpp.o
[ 44%] Building CXX object CMakeFiles/xmrig-nvidia.dir/src/net/SubmitResult.cpp.o
[ 46%] Building CXX object CMakeFiles/xmrig-nvidia.dir/src/net/Url.cpp.o
[ 48%] Building CXX object CMakeFiles/xmrig-nvidia.dir/src/nvidia/CudaCLI.cpp.o
[ 51%] Building CXX object CMakeFiles/xmrig-nvidia.dir/src/Options.cpp.o
[ 53%] Building CXX object CMakeFiles/xmrig-nvidia.dir/src/Platform.cpp.o
[ 55%] Building CXX object CMakeFiles/xmrig-nvidia.dir/src/Summary.cpp.o
[ 58%] Building CXX object CMakeFiles/xmrig-nvidia.dir/src/workers/CudaWorker.cpp.o
[ 60%] Building CXX object CMakeFiles/xmrig-nvidia.dir/src/workers/GpuThread.cpp.o
[ 62%] Building CXX object CMakeFiles/xmrig-nvidia.dir/src/workers/Handle.cpp.o
[ 65%] Building CXX object CMakeFiles/xmrig-nvidia.dir/src/workers/Hashrate.cpp.o
[ 67%] Building CXX object CMakeFiles/xmrig-nvidia.dir/src/workers/Workers.cpp.o
[ 69%] Building CXX object CMakeFiles/xmrig-nvidia.dir/src/xmrig.cpp.o
[ 72%] Building CXX object CMakeFiles/xmrig-nvidia.dir/src/App_unix.cpp.o
[ 74%] Building CXX object CMakeFiles/xmrig-nvidia.dir/src/Cpu_unix.cpp.o
[ 76%] Building CXX object CMakeFiles/xmrig-nvidia.dir/src/Platform_unix.cpp.o
[ 79%] Building CXX object CMakeFiles/xmrig-nvidia.dir/src/nvidia/NvmlApi.cpp.o
[ 81%] Building C object CMakeFiles/xmrig-nvidia.dir/src/crypto/c_keccak.c.o
[ 83%] Building C object CMakeFiles/xmrig-nvidia.dir/src/crypto/c_groestl.c.o
[ 86%] Building C object CMakeFiles/xmrig-nvidia.dir/src/crypto/c_blake256.c.o
[ 88%] Building C object CMakeFiles/xmrig-nvidia.dir/src/crypto/c_jh.c.o
[ 90%] Building C object CMakeFiles/xmrig-nvidia.dir/src/crypto/c_skein.c.o
[ 93%] Building CXX object CMakeFiles/xmrig-nvidia.dir/src/crypto/CryptoNight.cpp.o
[ 95%] Building CXX object CMakeFiles/xmrig-nvidia.dir/src/log/SysLog.cpp.o
[ 97%] Building CXX object CMakeFiles/xmrig-nvidia.dir/src/api/Httpd.cpp.o
/home/jeremy/xmrig-nvidia/src/api/Httpd.cpp:52:13: warning: Value MHD_USE_EPOLL_LINUX_ONLY is deprecated, use MHD_USE_EPOLL
         flags = MHD_USE_EPOLL_LINUX_ONLY | MHD_USE_EPOLL_INTERNALLY_LINUX_ONLY;
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/jeremy/xmrig-nvidia/src/api/Httpd.cpp:52:13: warning: Value MHD_USE_EPOLL_INTERNALLY_LINUX_ONLY is deprecated, use MHD_USE_EPOLL_INTERNALLY
         flags = MHD_USE_EPOLL_LINUX_ONLY | MHD_USE_EPOLL_INTERNALLY_LINUX_ONLY;
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                    
[100%] Linking CXX executable xmrig-nvidia
[100%] Built target xmrig-nvidia

**Comment by dirtydavemcgee** [comment]
config.json
{
    "algo": "cryptonight",
    "background": false,
    "colors": false,
    "donate-level": 0,
    "log-file": "cryptonight",
    "print-time": 60,
    "retries": 5,
    "retry-pause": 5,
    "syslog": false,
    "threads": [
        {
            "index": 0,
            "threads": 26,
            "blocks": 39,
            "bfactor": 0,
            "bsleep": 0,
            "affine_to_cpu": false
        },
        {
            "index": 1,
            "threads": 64,
            "blocks": 6,
            "bfactor": 0,
            "bsleep": 0,
            "affine_to_cpu": false
        }
    ],
    "pools": [
        {
            "url": "my.proxy.address:8080",
            "user": "",
            "pass": "main",
            "keepalive": true,
            "nicehash": false,
            "variant": 1
        }
    ],
    "api": {
        "port": 8080,
        "access-token": null,
        "worker-id": "main"
    }
}

**Comment by dirtydavemcgee** [comment]
./xmrig-nvidia 
 * VERSIONS:     XMRig/2.6.1 libuv/1.9.1 CUDA/9.10 gcc/6.3.0
 * CPU:          Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz (1) x64 AES-NI
 * GPU #0:       GeForce GTX 970 @ 1367/3505 MHz 26x39 0x0 arch:52 SMX:13
 * GPU #1:       GeForce GTX 650 @ 1058/2500 MHz 64x6 0x0 arch:30 SMX:2
 * ALGO:         cryptonight, donate=1%
 * POOL #1:      my.proxy.address:8080
 * API PORT:     8080
 * COMMANDS:     'h' hashrate, 'e' health, 'p' pause, 'r' resume
[2018-05-28 10:56:31] use pool miner.broke-it.net:8080 13.59.153.139
[2018-05-28 10:56:31] new job from miner.broke-it.net:8080 diff 5000
[2018-05-28 10:56:34] accepted (1/0) diff 5000 (55 ms)
<I pressed e here>
[2018-05-28 10:56:35]  * GPU #0: 1417/3004 MHz 99W 58C FAN 0%
[2018-05-28 10:56:35]  * GPU #1: 42C FAN 21%
<I pressed h here>
[2018-05-28 10:56:37] speed 10s/60s/15m (null) n/a n/a H/s
Segmentation fault

**Comment by dirtydavemcgee** [comment]
Problem does not exist in xmrig-cpu

**Comment by k0ste** [comment]
I guess this is the same issue like https://github.com/xmrig/xmrig-amd/issues/101.
@dirtydavemcgee, try to change `colors` to `true`.

**Comment by dirtydavemcgee** [comment]
No effect, colors dont display either.

**Comment by k0ste** [comment]
Try to use one card. In `xmrig-amd` this issue is reproducible only when more then one gpu's.

**Comment by dirtydavemcgee** [comment]
So, it works if I don't try to press H in the console
This is fine for me, as it runs as a service on my machine anyway.

@main:~/xmrig-nvidia/build$ ./xmrig-nvidia 
 * VERSIONS:     XMRig/2.6.1 libuv/1.9.1 CUDA/9.10 gcc/6.3.0
 * CPU:          Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz (1) x64 AES-NI
 * GPU #0:       GeForce GTX 970 @ 1367/3505 MHz 26x39 0x0 arch:52 SMX:13
 * GPU #1:       GeForce GTX 650 @ 1058/2500 MHz 64x6 0x0 arch:30 SMX:2
 * ALGO:         cryptonight, donate=1%
 * POOL #1:      MY.PROXY.ADDRESS:8080
 * API PORT:     8080
 * COMMANDS:     'h' hashrate, 'e' health, 'p' pause, 'r' resume
[2018-06-01 00:11:32] use pool miner.broke-it.net:8080 13.59.153.139
[2018-06-01 00:11:32] new job from miner.broke-it.net:8080 diff 5000
[2018-06-01 00:11:39] accepted (1/0) diff 5000 (54 ms)
[2018-06-01 00:11:54] accepted (2/0) diff 5000 (55 ms)
[2018-06-01 00:11:54] accepted (3/0) diff 5000 (55 ms)
[2018-06-01 00:12:01] accepted (4/0) diff 5000 (56 ms)
[2018-06-01 00:12:07] new job from miner.broke-it.net:8080 diff 8820
[2018-06-01 00:12:23] new job from miner.broke-it.net:8080 diff 8820
[2018-06-01 00:12:40] accepted (5/0) diff 8820 (56 ms)
[2018-06-01 00:12:41] speed 10s/60s/15m 614.2 613.9 n/a H/s max: 617.3 H/s
[2018-06-01 00:12:41]  * GPU #0: 1417/3004 MHz 106W 72C FAN 26%
[2018-06-01 00:12:41]  * GPU #1: 58C FAN 24%
[2018-06-01 00:12:49] accepted (6/0) diff 8820 (56 ms)
[2018-06-01 00:12:52] new job from miner.broke-it.net:8080 diff 7140
[2018-06-01 00:12:52] accepted (7/0) diff 8820 (78 ms
