### ISSUE TITLE
Does't compile on ubuntu

### ISSUE THREAD

**Issue by rcrahul60** [xmrig/xmrig-nvidia#175]
CMakeFiles/xmrig-nvidia.dir/build.make:1059: recipe for target 'xmrig-nvidia' failed
make[2]: *** [xmrig-nvidia] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/xmrig-nvidia.dir/all' failed
make[1]: *** [CMakeFiles/xmrig-nvidia.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by zocker-160** [comment]
Ubuntu version?
I compiled on Ubuntu 16.04.1 and Kernel 4.15.0-15 a few minutes ago without any problems.

**Comment by rcrahul60** [comment]
now its working
