### ISSUE TITLE
No 2.6.2 for nvidia?

### ISSUE THREAD

**Issue by TomKeyser** [xmrig/xmrig-nvidia#177]
just went to update miners for mining Stellite... your nvidia doesn't work after the latest fork.

**Comment by GrannyCryptomaster** [comment]
Yep, it needs update asap for the new algos: cn-fast, cn-lite-v7 etc

**Comment by xmrig** [comment]
Implemented in [v2.7.0-beta](https://github.com/xmrig/xmrig-nvidia/releases/tag/v2.7.0-beta) release.
