### ISSUE TITLE
does it work with cn fast?

### ISSUE THREAD

**Issue by aleqx** [xmrig/xmrig-nvidia#180]
The new Masari uses CN Fast. I see no new releases so I take it that xmrig-NVIDIA does not support it?

**Comment by DrStein99** [comment]
Looks like your answer is probably no.  Someone needs to compile a new version.

**Comment by TOGM** [comment]
cn fast would be nice, i know a lot of people like xmrig's work.

**Comment by xmrig** [comment]
Implemented in [v2.7.0-beta](https://github.com/xmrig/xmrig-nvidia/releases/tag/v2.7.0-beta) release.
