### ISSUE TITLE
cryptonight_extra_cpu_final: 375 unspecified launch error on 1 of 5 gpu's

### ISSUE THREAD

**Issue by griefage** [xmrig/xmrig-nvidia#186]
![errar](https://user-images.githubusercontent.com/35741937/43942129-cbb7393c-9c44-11e8-82d5-e2b9005b1e2e.png)

I'm running xmrig nvidia v2.7.0-beta and on 1 of my 6  gtx 1070ti gpu's i keep getting this error after hours of running fine. the other 5 gpu's run flawlessly.

i first started dropping my overclock on this gpu considerably but the crash would still occur.
i then reduced my thread count from 32 to 30, no change.
then i reduced the bfactor to 7 and it did drop my hashrate but still same error after a few hours.

here are the settings for my 1070ti's:

            "threads": 32,
            "blocks": 76,
            "bfactor": 8,
            "bsleep": 25,
            "sync_mode": 3,
            "affine_to_cpu": false

would appreciate any advice or explanation of that error code.

I have another two 1070ti's running 24/7 in a pc with these same settings with no issue.

Never had any issues with this particular gpu with equihash or x16r, so i doubt its the riser or hardware, always run it cool. nvidia driver 398.82.

**Comment by Xingez** [comment]
Same issue with my 1080ti, seems to happen less when mining cryptonight/msr.

**Comment by griefage** [comment]
i was able to get to to run stable by decreasing the power limit further and the core clock lower.
