### ISSUE TITLE
Low performance compared to XMR-STAK-NVIDIA

### ISSUE THREAD

**Issue by rmbb** [xmrig/xmrig-nvidia#19]
Hi, I have XMR-STAK-NVIDIA running on my computer.
My setup is 6 x NVIDIA 1070 GPU.

Those are my settings for all 6 GPUs 1070 on XMR-STACK-NVIDIA:

Threads: 80
Blocks: 30
Bfactor: 6
Bsleep: 25

Those are the results I get stable with temperature around 60ºC:

![image](https://user-images.githubusercontent.com/32343762/30937984-6e595224-a3d0-11e7-92c3-df577501d2ed.png)

Now using XMRIG-NVIDIA with the following settings:

Threads: 80
Blocks: 30
Bfactor: 6
Bsleep: 25
Keepalive: true
Nicehash: false

Those are the results I get:

![image](https://user-images.githubusercontent.com/32343762/30939018-fc6cfd74-a3d3-11e7-902c-c1a6bdcac532.png)

As you can see it's a huge difference, around 600 H/s less when comparing to XMR-STAK-NVIDIA.

Thanks.

**Comment by xmrig** [comment]
Please press `h` to see per card hashrate. Also better to see first lines when miner start.
Thank you.

**Comment by NicerDicerPlus** [comment]
Go low on blocks and high on treads My GTX 1060 
"threads": 16,
 "blocks": 72,

**Comment by kilid** [comment]
nice results , could you please write an example on how to put these setting in the command line
