### ISSUE TITLE
error with cuda_extra.cu

### ISSUE THREAD

**Issue by lexphor** [xmrig/xmrig-nvidia#2]
Hello,
I'm on ubuntu 16.04
Here is my configuration and the error message:
 * VERSIONS:     XMRig/2.3.0-beta1 libuv/1.8.0 CUDA/8.0 gcc/5.4.0
 * CPU:          Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz x64 AES-NI
 * GPU #0:       GeForce GTX 950A 42x15 f:0 s:0 arch:50 smx:5
 * ALGO:         cryptonight, donate=5%

I get: 
GPU 0: the launch timed out and was terminated
/home/user/xmrig-nvidia/src/nvidia/cuda_extra.cu line 246

During make, I get the following warnings:

[  2%] Building NVCC (Device) object CMakeFiles/xmrig-cuda.dir/src/nvidia/xmrig-cuda_generated_cuda_extra.cu.o
cc1: warning: command line option ‘-fno-rtti’ is valid for C++/ObjC++ but not for C
cc1: warning: command line option ‘-fno-rtti’ is valid for C++/ObjC++ but not for C
cc1: warning: command line option ‘-fno-rtti’ is valid for C++/ObjC++ but not for C
cc1: warning: command line option ‘-fno-rtti’ is valid for C++/ObjC++ but not for C
cc1: warning: command line option ‘-fno-rtti’ is valid for C++/ObjC++ but not for C
cc1: warning: command line option ‘-fno-rtti’ is valid for C++/ObjC++ but not for C
cc1: warning: command line option ‘-fno-rtti’ is valid for C++/ObjC++ but not for C
cc1: warning: command line option ‘-fno-rtti’ is valid for C++/ObjC++ but not for C
/home/user/xmrig-nvidia/src/nvidia/cuda_extra.cu: In function ‘void cryptonight_extra_cpu_final(nvid_ctx*, uint32_t, uint64_t, uint32_t*, uint32_t*)’:
/home/user/xmrig-nvidia/src/nvidia/cuda_extra.cu:250:19: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  for(int i=0; i < *rescount; i++)
                   ^
and towards the end, another warning:

[ 91%] Building C object CMakeFiles/xmrig-nvidia.dir/src/crypto/c_skein.c.o
/home/user/xmrig-nvidia/src/crypto/c_skein.c: In function ‘Skein_512_Final’:
/home/user/xmrig-nvidia/src/crypto/c_skein.c:574:9: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
         ((u64b_t *)ctx->b)[0]= Skein_Swap64((u64b_t) i); /* build the counter block */
         ^

I tried purging cuda and reinstalling then recompiling but still get the same warnings and the miner doesn't work.

Any help is appreciated.

Also, a big thanks for the amazing work you're doing. I'm already using your CPU version, seriously the best miner ever. I hope you'd release the amd version soon.

**Comment by xmrig** [comment]
If you place config.json in same dirrectory with binary or specify path to this file via command line options, miner will update your config, try reduce threads to 32 or lower values.

Example:
```json
    "threads": [
        {
            "index": 0,
            "threads": 32,
            "blocks": 15,
            "bfactor": 0,
            "bsleep": 0
        }
    ],
```
Please write back with threads count it start working, current auto-configuration too much aggressive, I know about it, will fix it soon.
Thank you.

**Comment by lexphor** [comment]
The miner is now working fine with 32 threads and 15 blocks. 
Thanks a lot!
Sorry if noob question here, but how exactly do I figure out the best threads/blocks configuration? It can't be like throwing random numbers there I hope.

Seriously, thanks a bunch for you prompt reply and your amazing work. Highly appreciate it.

**Comment by lexphor** [comment]
Thanks for the nice explanation. 

A bit off topic, but does this miner also support the cryptonight-light algo?

**Comment by xmrig** [comment]
At this moment no, will be added later.

**Comment by xmrig** [comment]
I added cryptonight-light algo, single binary for both algos.

**Comment by esfomeado** [comment]
GTX 950M/960M - 32x15 crashes somehow it is too intense for this cards?
16x15 works but with a poor hashrate.

**Comment by xmrig** [comment]
What exactly error? You can use numbers like 31, 30, ... for thread count, no need half it.

**Comment by esfomeado** [comment]
GPU #0: unspecified launch failure
cryptonight_extra_cpu_final line 247

Yes I tried 31,30,... But only around 16 seem to work with a hashrate of 70.

**Comment by esfomeado** [comment]
20x15 seems to be perfect for the GTX 950M.
25~26x15 crashes.
The same happens on xmr-stak-nvidia.
Not sure why this happens since the memory usage is below 85%. There should be another limitations at least on the mobile variants.

**Comment by esfomeado** [comment]
Not sure if related:
https://github.com/KlausT/ccminer-cryptonight/commit/3af4f8cd529cd77601f6ec1cce41b51c4b4730a7
