### ISSUE TITLE
health only when press "e"

### ISSUE THREAD

**Issue by Antonio6666** [xmrig/xmrig-nvidia#204]
* ABOUT        XMRig-NVIDIA/2.8.0-rc gcc/6.4.0
 * LIBS         libuv/1.18.0 CUDA/10.0 OpenSSL/1.1.0g microhttpd/0.9.59 
 * CPU          AMD Ryzen 5 1600 Six-Core Processor             x64 AES

I compiled version XMRig-NVIDIA/2.8.0-rc on ubuntu 17.04 (cuda 10) it works but with the old version every x time GPU temperature was displayed with this new version is not automatically displayed, only  when i mannually press the key "e"

**Comment by xmrig** [comment]
Fixed. This code was accidentally removed in v2.7.0-beta.
Thank you.

**Comment by xmrig** [comment]
Fix included to https://github.com/xmrig/xmrig-nvidia/releases/tag/v2.8.1
