### ISSUE TITLE
Compilation in Ubuntu with problems

### ISSUE THREAD

**Issue by Djago** [xmrig/xmrig-nvidia#208]
Hi

I have compiled previous version without a glitch in a 16.04 following instructions here.
But with this new version I had to give the -DNVML_INCLUDE_DIR=/path, the -DWITH_TLS=OFF (I don't need it and I don't have OpenSSH installed), and I'm getting a fatal error: nvml.h: no such file or directory.
Why the difference between previous and new version?
* 16.04 server (x64)
* nVidia GT550Ti
* CUDA release 7.5, V7.5.17
* nVidia driver 384.130

**Comment by xmrig** [comment]
There is no difference, except you may update cmake (unlikely), `FindCUDA.cmake` shipped with cmake, also usually don't need specify `-DNVML_INCLUDE_DIR` at all. Need more information, how you install CUDA, cmake output, make output, etc.
Thank you.

**Comment by Djago** [comment]
I've installed a clean Ubuntu Server 16.04. I've installed as per your instructions on how to build on 16.04, except that line of cmake. I'm using:
cmake .. -DCUDA_ARCH="20;30;50" -DNVML_INCLUDE_DIR=/usr/lib/nvidia-384 -DWITH_TLS=OFF
If I don't use the -DNVML_INCLUDE_DIR=/usr/lib/nvidia-384 I get:

> -- Could NOT find NVML (missing:  NVML_INCLUDE_DIR)

If I don't use -DWITH_TLS=OFF I get:

> -- Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the system variable OPENSSL_ROOT_DIR (missing:  OPENSSL_LIBRARIES OPENSSL_INCLUDE_DIR)
(but this is something I don't need, so it's not a problem).

Then:
>root@Rig1:/home/djago/xmrig-nvidia/build# cmake .. -DCUDA_ARCH="20;30;50" -DNVML_INCLUDE_DIR=/usr/lib/nvidia-384 -DWITH_TLS=OFF
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found UV: /usr/lib/x86_64-linux-gnu/libuv.a
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found CUDA: /usr (found suitable version "7.5", minimum required is "7.5")
-- Found NVML: /usr/lib/nvidia-384
-- Looking for syslog.h
-- Looking for syslog.h - found
-- Found MHD: /usr/lib/x86_64-linux-gnu/libmicrohttpd.so
-- Configuring done
-- Generating done
-- Build files have been written to: /home/djago/xmrig-nvidia/build

After that:

> root@Rig1:/home/djago/xmrig-nvidia/build# make
[  2%] Building NVCC (Device) object CMakeFiles/xmrig-cuda.dir/src/nvidia/xmrig-cuda_generated_cuda_extra.cu.o
[  4%] Building NVCC (Device) object CMakeFiles/xmrig-cuda.dir/src/nvidia/xmrig-cuda_generated_cuda_core.cu.o
Scanning dependencies of target xmrig-cuda
[  6%] Linking CXX static library libxmrig-cuda.a
[  6%] Built target xmrig-cuda
Scanning dependencies of target xmrig-nvidia
[  8%] Building CXX object CMakeFiles/xmrig-nvidia.dir/src/api/NetworkState.cpp.o
[ 10%] Building CXX object CMakeFiles/xmrig-nvidia.dir/src/App.cpp.o
[ 12%] Building CXX object CMakeFiles/xmrig-nvidia.dir/src/common/config/CommonConfig.cpp.o
[ 14%] Building CXX object CMakeFiles/xmrig-nvidia.dir/src/common/config/ConfigLoader.cpp.o
[ 16%] Building CXX object CMakeFiles/xmrig-nvidia.dir/src/common/config/ConfigWatcher.cpp.o
[ 18%] Building CXX object CMakeFiles/xmrig-nvidia.dir/src/common/Console.cpp.o
[ 20%] Building CXX object CMakeFiles/xmrig-nvidia.dir/src/common/cpu/BasicCpuInfo.cpp.o
[ 22%] Building CXX object CMakeFiles/xmrig-nvidia.dir/src/common/cpu/Cpu.cpp.o
[ 24%] Building CXX object CMakeFiles/xmrig-nvidia.dir/src/common/crypto/Algorithm.cpp.o
[ 26%] Building CXX object CMakeFiles/xmrig-nvidia.dir/src/common/crypto/keccak.cpp.o
[ 28%] Building CXX object CMakeFiles/xmrig-nvidia.dir/src/common/log/BasicLog.cpp.o
[ 30%] Building CXX object CMakeFiles/xmrig-nvidia.dir/src/common/log/ConsoleLog.cpp.o
[ 32%] Building CXX object CMakeFiles/xmrig-nvidia.dir/src/common/log/FileLog.cpp.o
[ 34%] Building CXX object CMakeFiles/xmrig-nvidia.dir/src/common/log/Log.cpp.o
[ 36%] Building CXX object CMakeFiles/xmrig-nvidia.dir/src/common/net/Client.cpp.o
[ 38%] Building CXX object CMakeFiles/xmrig-nvidia.dir/src/common/net/Job.cpp.o
[ 40%] Building CXX object CMakeFiles/xmrig-nvidia.dir/src/common/net/Pool.cpp.o
[ 42%] Building CXX object CMakeFiles/xmrig-nvidia.dir/src/common/net/strategies/FailoverStrategy.cpp.o
[ 44%] Building CXX object CMakeFiles/xmrig-nvidia.dir/src/common/net/strategies/SinglePoolStrategy.cpp.o
[ 46%] Building CXX object CMakeFiles/xmrig-nvidia.dir/src/common/net/SubmitResult.cpp.o
[ 48%] Building CXX object CMakeFiles/xmrig-nvidia.dir/src/common/Platform.cpp.o
[ 50%] Building CXX object CMakeFiles/xmrig-nvidia.dir/src/core/Config.cpp.o
[ 52%] Building CXX object CMakeFiles/xmrig-nvidia.dir/src/core/Controller.cpp.o
[ 54%] Building CXX object CMakeFiles/xmrig-nvidia.dir/src/net/Network.cpp.o
[ 56%] Building CXX object CMakeFiles/xmrig-nvidia.dir/src/net/strategies/DonateStrategy.cpp.o
[ 58%] Building CXX object CMakeFiles/xmrig-nvidia.dir/src/nvidia/CudaCLI.cpp.o
[ 60%] Building CXX object CMakeFiles/xmrig-nvidia.dir/src/Summary.cpp.o
[ 62%] Building CXX object CMakeFiles/xmrig-nvidia.dir/src/workers/CudaWorker.cpp.o
[ 64%] Building CXX object CMakeFiles/xmrig-nvidia.dir/src/workers/CudaThread.cpp.o
[ 66%] Building CXX object CMakeFiles/xmrig-nvidia.dir/src/workers/Handle.cpp.o
[ 68%] Building CXX object CMakeFiles/xmrig-nvidia.dir/src/workers/Hashrate.cpp.o
[ 70%] Building CXX object CMakeFiles/xmrig-nvidia.dir/src/workers/Workers.cpp.o
[ 72%] Building CXX object CMakeFiles/xmrig-nvidia.dir/src/xmrig.cpp.o
[ 74%] Building CXX object CMakeFiles/xmrig-nvidia.dir/src/App_unix.cpp.o
[ 76%] Building CXX object CMakeFiles/xmrig-nvidia.dir/src/common/Platform_unix.cpp.o
[ 78%] Building CXX object CMakeFiles/xmrig-nvidia.dir/src/nvidia/NvmlApi.cpp.o
/home/djago/xmrig-nvidia/src/nvidia/NvmlApi.cpp:24:18: fatal error: nvml.h: No such file or directory
compilation terminated.
CMakeFiles/xmrig-nvidia.dir/build.make:902: recipe for target 'CMakeFiles/xmrig-nvidia.dir/src/nvidia/NvmlApi.cpp.o' failed
make[2]: *** [CMakeFiles/xmrig-nvidia.dir/src/nvidia/NvmlApi.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/xmrig-nvidia.dir/all' failed
make[1]: *** [CMakeFiles/xmrig-nvidia.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by xmrig** [comment]
`-- Could NOT find NVML (missing: NVML_INCLUDE_DIR)` it's not an error, it just warning, without NVML miner will work, but information about GPU will not available (temperature/power/...).

**Comment by Djago** [comment]
But it's not generating any executable! Also, why this build has error and previous build compiled ok?

**Comment by Gilly1970** [comment]
Update to cuda 8 or 9 and make sure all dependencies are installed and up to date as well

cmake .. -DUSE_CUDA=ON -DCUDA_ARCH="30;50;60"

**Comment by Djago** [comment]
Can't use 9 because it's not compatible with Fermi chips. 
Why should I chage from 7.5? It was working on previous version

**Comment by Djago** [comment]
I've updgraded to CUDA 8 and now it's working ok. Thanks
