### ISSUE TITLE
How to run after Make

### ISSUE THREAD

**Issue by Jazon22** [xmrig/xmrig-nvidia#21]
Hello,

I followed the directions to build, and believe it was successful.

The last two messages are as follows.

[100%] Linking CXX executable xmrig-nvidia
[100%] Built target xmrig-nvidia

I've researched for an hour but can't figure out how to configure it and then run it.  Can you link the directions to configure and run xmrig-nvidia?

Running Unbuntu 17.04 and used these commands to build.

sudo apt-get install git build-essential cmake libuv1-dev nvidia-cuda-dev nvidia-cuda-toolkit gcc-5 g++-5
git clone https://github.com/xmrig/xmrig-nvidia.git
cd xmrig-nvidia
mkdir build
cd build
cmake .. -DCMAKE_C_COMPILER=gcc-5 -DCMAKE_CXX_COMPILER=g++-5
make

Thanks

**Comment by Jazon22** [comment]
I figured it out.

Thanks

**Comment by m-henderson** [comment]
I am on windows 10 and cant figure out how to run  it after building it. any suggestions ? i figured they would put instructions in the repo

**Comment by Jazon22** [comment]
Can't remember at the moment.  I can check my setup after work if you still need help.

**Comment by m-henderson** [comment]
that would be great. thanks
