### ISSUE TITLE
Error on Windows build

### ISSUE THREAD

**Issue by MarioPeh** [xmrig/xmrig-nvidia#23]
Hello,
i have this error on Windows build.

`C:\xmrig\xmrig-nvidia-master\build>msbuild xmrig-nvidia.sln /p:Configuration=Release
Microsoft (R)-Buildmodul, Version 15.3.409.57025 für .NET Framework
Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.

Die Projekte in dieser Projektmappe werden nacheinander erstellt. Um eine parallele Erstellung zu ermöglichen, müssen Sie den Schalter "/m" hinzufügen.
Der Buildvorgang wurde am 05.10.2017 09:34:15 gestartet.
Projekt "C:\xmrig\xmrig-nvidia-master\build\xmrig-nvidia.sln" auf Knoten "1" (Standardziele).
ValidateSolutionConfiguration:
  Die Projektmappenkonfiguration "Release|x64" wird erstellt.
ValidateProjects:
  Das Projekt "ALL_BUILD" ist in der Projektmappenkonfiguration "Release|x64" nicht zum Erstellen ausgewählt.
Das Projekt "C:\xmrig\xmrig-nvidia-master\build\xmrig-nvidia.sln" (1) erstellt "C:\xmrig\xmrig-nvidia-master\build\ZERO_CHECK.vcxproj" (2) auf Knoten "1" (Standardziele).
InitializeBuildStatus:
  "x64\Release\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild" wird erstellt, da "AlwaysCreate" angegeben wurde.
CustomBuild:
  Alle Ausgaben sind aktuell.
FinalizeBuildStatus:
  Die Datei "x64\Release\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild" wird gelöscht.
  Aktualisieren des Timestamps von "x64\Release\ZERO_CHECK\ZERO_CHECK.tlog\ZERO_CHECK.lastbuildstate".
Die Erstellung von Projekt "C:\xmrig\xmrig-nvidia-master\build\ZERO_CHECK.vcxproj" ist abgeschlossen (Standardziele).

Das Projekt "C:\xmrig\xmrig-nvidia-master\build\xmrig-nvidia.sln" (1) erstellt "C:\xmrig\xmrig-nvidia-master\build\src\3rdparty\jansson\jansson.vcxproj.metaproj" (3) auf Knoten "1" (Standardziele).
Das Projekt "C:\xmrig\xmrig-nvidia-master\build\src\3rdparty\jansson\jansson.vcxproj.metaproj" (3) erstellt "C:\xmrig\xmrig-nvidia-master\build\src\3rdparty\jansson\jansson.vcxproj" (4) auf Knoten "1" (Standardziele).
InitializeBuildStatus:
  "jansson.dir\Release\jansson.tlog\unsuccessfulbuild" wird erstellt, da "AlwaysCreate" angegeben wurde.
CustomBuild:
  Alle Ausgaben sind aktuell.
ClCompile:
  Alle Ausgaben sind aktuell.
Lib:
  Alle Ausgaben sind aktuell.
  jansson.vcxproj -> C:\xmrig\xmrig-nvidia-master\build\src\3rdparty\jansson\Release\jansson.lib
FinalizeBuildStatus:
  Die Datei "jansson.dir\Release\jansson.tlog\unsuccessfulbuild" wird gelöscht.
  Aktualisieren des Timestamps von "jansson.dir\Release\jansson.tlog\jansson.lastbuildstate".
Die Erstellung von Projekt "C:\xmrig\xmrig-nvidia-master\build\src\3rdparty\jansson\jansson.vcxproj" ist abgeschlossen (Standardziele).

Die Erstellung von Projekt "C:\xmrig\xmrig-nvidia-master\build\src\3rdparty\jansson\jansson.vcxproj.metaproj" ist abgeschlossen (Standardziele).

Das Projekt "C:\xmrig\xmrig-nvidia-master\build\xmrig-nvidia.sln" (1) erstellt "C:\xmrig\xmrig-nvidia-master\build\xmrig-cuda.vcxproj.metaproj" (5) auf Knoten "1" (Standardziele).
Das Projekt "C:\xmrig\xmrig-nvidia-master\build\xmrig-cuda.vcxproj.metaproj" (5) erstellt "C:\xmrig\xmrig-nvidia-master\build\xmrig-cuda.vcxproj" (6) auf Knoten "1" (Standardziele).
InitializeBuildStatus:
  Aktualisieren des Timestamps von "xmrig-cuda.dir\Release\xmrig-cuda.tlog\unsuccessfulbuild".
CustomBuild:
  Building NVCC (Device) object CMakeFiles/xmrig-cuda.dir/src/nvidia/Release/xmrig-cuda_generated_cuda_core.cu.obj
  CMake Error at xmrig-cuda_generated_cuda_core.cu.obj.Release.cmake:222 (message):
    Error generating
    C:/xmrig/xmrig-nvidia-master/build/CMakeFiles/xmrig-cuda.dir/src/nvidia/Release/xmrig-cuda_generated_cuda_core.cu.obj

C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" wurde mit dem Code 1 beendet. [C:\xmrig\xmrig-nvidia-master\build\xmrig
-cuda.vcxproj]
Die Erstellung des Projekts "C:\xmrig\xmrig-nvidia-master\build\xmrig-cuda.vcxproj" ist abgeschlossen (Standardziele) -- FEHLER.

Die Erstellung des Projekts "C:\xmrig\xmrig-nvidia-master\build\xmrig-cuda.vcxproj.metaproj" ist abgeschlossen (Standardziele) -- FEHLER.

Die Erstellung des Projekts "C:\xmrig\xmrig-nvidia-master\build\xmrig-nvidia.sln" ist abgeschlossen (Standardziele) -- FEHLER.

Fehler beim Buildvorgang.

"C:\xmrig\xmrig-nvidia-master\build\xmrig-nvidia.sln" (Standardziel) (1) ->
"C:\xmrig\xmrig-nvidia-master\build\xmrig-cuda.vcxproj.metaproj" (Standardziel) (5) ->
"C:\xmrig\xmrig-nvidia-master\build\xmrig-cuda.vcxproj" (Standardziel) (6) ->
(CustomBuild Ziel) ->
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" wurde mit dem Code 1 beendet. [C:\xmrig\xmrig-nvidia-master\build\xmr
ig-cuda.vcxproj]

    0 Warnung(en)
    1 Fehler

Verstrichene Zeit 00:00:10.13`

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig-nvidia/wiki/Windows-Build
