### ISSUE TITLE
Reload configuration after putting new one using API

### ISSUE THREAD

**Issue by WURMiL** [xmrig/xmrig-nvidia#230]
Hello,

I've used API to push new configuration to running xmrig-nvidia 2.8.4 (HTTP PUT to /1/config). API returns 200 OK, on the output windows appears "configuration saved to: C:\...\config.json", configuration file was successfully changed, but changes take effect only after restarting the application. Basically I only want to change the connected pool. Is anyhow possible to reload configuration without manual restarting the xmrig?
Thank you ;)

**Comment by xmrig** [comment]
Now this feature available for all miners https://github.com/xmrig/xmrig/issues/939
Thank you.
