### ISSUE TITLE
Can not compile, cmake can not find CUDA_LIB

### ISSUE THREAD

**Issue by renheren** [xmrig/xmrig-nvidia#240]
> -- Found CUDA: /usr/local/cuda (found suitable version "9.2", minimum required is "7.5")
-- Found NVML: /usr/local/cuda/include
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so (found version "1.0.2g")
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- Looking for syslog.h
-- Looking for syslog.h - found
-- Found MHD: /usr/lib/x86_64-linux-gnu/libmicrohttpd.so
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
CUDA_LIB
    linked by target "xmrig-nvidia" in directory /xmrig-nvidia
>
>-- Configuring incomplete, errors occurred!
See also "/xmrig-nvidia/build/CMakeFiles/CMakeOutput.log".
See also "/xmrig-nvidia/build/CMakeFiles/CMakeError.log".

While for version 2.8.3, things went well. It seems it is related to commit [2e23e1e](https://github.com/xmrig/xmrig-nvidia/commit/2e23e1ee64b1424cf8735b8a6826882cc2ba55fb#diff-d77f46a67237a37b9c4eae17e6a1b741).
Have I missed something for compilation?

**Comment by xorz57** [comment]
- Do you have an `nvidia` graphics card?
- Did you install `nvidia` drivers?
- Did you install `nvidia-cuda-toolkit`?

If the answer to all above is yes, then there is probably a problem with `CMakeLists.txt`

**Comment by renheren** [comment]
@xorz57
I used docker image nvidia/cuda:9.2-devel for compilation.
I do have nvidia graphic cards and driver on the host.
There should be a nvidia-cuda-toolkit installed inside the docker image.

**Comment by xorz57** [comment]
@renheren Did you also try other versions of this docker image? I am asking this because I see that version 9.2 is [experimental](https://hub.docker.com/r/nvidia/cuda/) try version 10 and see if it works there. Maybe all of this is totally irrelevant but I think it's worth trying.

**Comment by barpaum** [comment]
@xorz57 
Actually, the one tagged as 9.2-devel is not experimental as that of 9.2-devel-ubuntu18.04.
I will try version 10 after upgrading nvidia driver to a higher version ( currently 396.54 ).

**Comment by renheren** [comment]
@xorz57
Actually, the one tagged as 9.2-devel is not experimental as that of 9.2-devel-ubuntu18.04.
I will try version 10 after upgrading nvidia driver to a higher version ( currently 396.54 ).

**Comment by renheren** [comment]
@xorz57 
I've upgarded nvidia driver to version 410. But there is no luckiness. The same error was shown with docker image of 10.0-devel.

**Comment by xorz57** [comment]
Then it's problem with CMakeLists.txt

**Comment by xorz57** [comment]
If you can log into your docker image with interactive terminal and use ccmake if possible to see all cmake variables/options.

**Comment by Perfect-Web** [comment]
any news on this ?

**Comment by KnightZhao** [comment]
try  cmake ..  -DCUDA_LIB=/cudapath/cuda-9.2/lib64  -DCUDA_TOOLKIT_ROOT_DIR=/cudapath/cuda-9.2

**Comment by KnightZhao** [comment]
but make have error

CMakeFiles/xmrig-nvidia.dir/src/App.cpp.o: In function `xmrig::App::App(xmrig::Process*)':
App.cpp:(.text+0x47e): undefined reference to `cuInit'
libxmrig-cuda.a(xmrig-cuda_generated_cuda_core.cu.o): In function `cryptonight_gpu_hash(nvid_ctx*, xmrig::Algo, xmrig::Variant, unsigned long, unsigned int)':
tmpxft_00002a22_00000000-5_cuda_core.compute_50.cudafe1.cpp:(.text+0x1e6): undefined reference to `cuModuleUnload'
tmpxft_00002a22_00000000-5_cuda_core.compute_50.cudafe1.cpp:(.text+0x26a): undefined reference to `cuModuleLoadDataEx'
tmpxft_00002a22_00000000-5_cuda_core.compute_50.cudafe1.cpp:(.text+0x286): undefined reference to `cuModuleGetFunction'
tmpxft_00002a22_00000000-5_cuda_core.compute_50.cudafe1.cpp:(.text+0x4a4): undefined reference to `cuGetErrorString'
tmpxft_00002a22_00000000-5_cuda_core.compute_50.cudafe1.cpp:(.text+0x68e): undefined reference to `cuGetErrorString'
libxmrig-cuda.a(xmrig-cuda_generated_cuda_core.cu.o): In function `void cryptonight_core_gpu_hash<(xmrig::Algo)0, (xmrig::Variant)12>(nvid_ctx*, unsigned int)':
tmpxft_00002a22_00000000-5_cuda_core.compute_50.cudafe1.cpp:(.text._Z25cryptonight_core_gpu_hashILN5xmrig4AlgoE0ELNS0_7VariantE12EEvP8nvid_ctxj[_Z25cryptonight_core_gpu_hashILN5xmrig4AlgoE0ELNS0_7VariantE12EEvP8nvid_ctxj]+0x3c0): undefined reference to `cuLaunchKernel_ptsz'
tmpxft_00002a22_00000000-5_cuda_core.compute_50.cudafe1.cpp:(.text._Z25cryptonight_core_gpu_hashILN5xmrig4AlgoE0ELNS0_7VariantE12EEvP8nvid_ctxj[_Z25cryptonight_core_gpu_hashILN5xmrig4AlgoE0ELNS0_7VariantE12EEvP8nvid_ctxj]+0x3d1): undefined reference to `cuCtxSynchronize'
tmpxft_00002a22_00000000-5_cuda_core.compute_50.cudafe1.cpp:(.text._Z25cryptonight_core_gpu_hashILN5xmrig4AlgoE0ELNS0_7VariantE12EEvP8nvid_ctxj[_Z25cryptonight_core_gpu_hashILN5xmrig4AlgoE0ELNS0_7VariantE12EEvP8nvid_ctxj]+0x767): undefined reference to `cuLaunchKernel_ptsz'
tmpxft_00002a22_00000000-5_cuda_core.compute_50.cudafe1.cpp:(.text._Z25cryptonight_core_gpu_hashILN5xmrig4AlgoE0ELNS0_7VariantE12EEvP8nvid_ctxj[_Z25cryptonight_core_gpu_hashILN5xmrig4AlgoE0ELNS0_7VariantE12EEvP8nvid_ctxj]+0x778): undefined reference to `cuCtxSynchronize'
tmpxft_00002a22_00000000-5_cuda_core.compute_50.cudafe1.cpp:(.text._Z25cryptonight_core_gpu_hashILN5xmrig4AlgoE0ELNS0_7VariantE12EEvP8nvid_ctxj[_Z25cryptonight_core_gpu_hashILN5xmrig4AlgoE0ELNS0_7VariantE12EEvP8nvid_ctxj]+0xa6b): undefined reference to `cuGetErrorString'
tmpxft_00002a22_00000000-5_cuda_core.compute_50.cudafe1.cpp:(.text._Z25cryptonight_core_gpu_hashILN5xmrig4AlgoE0ELNS0_7VariantE12EEvP8nvid_ctxj[_Z25cryptonight_core_gpu_hashILN5xmrig4AlgoE0ELNS0_7VariantE12EEvP8nvid_ctxj]+0xc29): undefined reference to `cuGetErrorString'
libxmrig-cuda.a(xmrig-cuda_generated_cuda_core.cu.o): In function `void cryptonight_core_gpu_hash<(xmrig::Algo)0, (xmrig::Variant)13>(nvid_ctx*, unsigned int)':
tmpxft_00002a22_00000000-5_cuda_core.compute_50.cudafe1.cpp:(.text._Z25cryptonight_core_gpu_hashILN5xmrig4AlgoE0ELNS0_7VariantE13EEvP8nvid_ctxj[_Z25cryptonight_core_gpu_hashILN5xmrig4AlgoE0ELNS0_7VariantE13EEvP8nvid_ctxj]+0x3c0): undefined reference to `cuLaunchKernel_ptsz'
tmpxft_00002a22_00000000-5_cuda_core.compute_50.cudafe1.cpp:(.text._Z25cryptonight_core_gpu_hashILN5xmrig4AlgoE0ELNS0_7VariantE13EEvP8nvid_ctxj[_Z25cryptonight_core_gpu_hashILN5xmrig4AlgoE0ELNS0_7VariantE13EEvP8nvid_ctxj]+0x3d1): undefined reference to `cuCtxSynchronize'
tmpxft_00002a22_00000000-5_cuda_core.compute_50.cudafe1.cpp:(.text._Z25cryptonight_core_gpu_hashILN5xmrig4AlgoE0ELNS0_7VariantE13EEvP8nvid_ctxj[_Z25cryptonight_core_gpu_hashILN5xmrig4AlgoE0ELNS0_7VariantE13EEvP8nvid_ctxj]+0x767): undefined reference to `cuLaunchKernel_ptsz'
tmpxft_00002a22_00000000-5_cuda_core.compute_50.cudafe1.cpp:(.text._Z25cryptonight_core_gpu_hashILN5xmrig4AlgoE0ELNS0_7VariantE13EEvP8nvid_ctxj[_Z25cryptonight_core_gpu_hashILN5xmrig4AlgoE0ELNS0_7VariantE13EEvP8nvid_ctxj]+0x778): undefined reference to `cuCtxSynchronize'
tmpxft_00002a22_00000000-5_cuda_core.compute_50.cudafe1.cpp:(.text._Z25cryptonight_core_gpu_hashILN5xmrig4AlgoE0ELNS0_7VariantE13EEvP8nvid_ctxj[_Z25cryptonight_core_gpu_hashILN5xmrig4AlgoE0ELNS0_7VariantE13EEvP8nvid_ctxj]+0xa6b): undefined reference to `cuGetErrorString'
tmpxft_00002a22_00000000-5_cuda_core.compute_50.cudafe1.cpp:(.text._Z25cryptonight_core_gpu_hashILN5xmrig4AlgoE0ELNS0_7VariantE13EEvP8nvid_ctxj[_Z25cryptonight_core_gpu_hashILN5xmrig4AlgoE0ELNS0_7VariantE13EEvP8nvid_ctxj]+0xc29): undefined reference to `cuGetErrorString'
libxmrig-cuda.a(xmrig-cuda_generated_cuda_extra.cu.o): In function `cryptonight_extra_cpu_init(nvid_ctx*, xmrig::Algo, unsigned long)':
tmpxft_00002995_00000000-5_cuda_extra.compute_50.cudafe1.cpp:(.text+0x581): undefined reference to `cuDeviceGet'
tmpxft_00002995_00000000-5_cuda_extra.compute_50.cudafe1.cpp:(.text+0x596): undefined reference to `cuCtxCreate_v2'
tmpxft_00002995_00000000-5_cuda_extra.compute_50.cudafe1.cpp:(.text+0xca8): undefined reference to `cuGetErrorString'
tmpxft_00002995_00000000-5_cuda_extra.compute_50.cudafe1.cpp:(.text+0xdc7): undefined reference to `cuGetErrorString'
collect2: error: ld returned 1 exit status
CMakeFiles/xmrig-nvidia.dir/build.make:1716: recipe for target 'xmrig-nvidia' failed
make[2]: *** [xmrig-nvidia] Error 1
CMakeFiles/Makefile2:142: recipe for target 'CMakeFiles/xmrig-nvidia.dir/all' failed
make[1]: *** [CMakeFiles/xmrig-nvidia.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by KnightZhao** [comment]
ln your/cudapath /usr/local/cuda
then 
- cmake ..    
- make

**Comment by jonathansd1** [comment]
+1 for this issue. I do not get this error on v2.11.0, but v2.13.0 and v2.14.0 both end with this error.

**Comment by KnightZhao** [comment]
I set the default cuda path, then make OK.

**Comment by Perfect-Web** [comment]
@xorz57 can we merge this into master pls ?

**Comment by xorz57** [comment]
@Perfect-Web I am not maintaining this repository. You should probably talk to @xmrig

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig-nvidia/pull/235#issuecomment-463040311

Miner now required NVRTC both in compile time and runtime, including libcuda.so (driver component) because new algorithms `cn/r` and `cn/wow` require runtime compilation. Probably docker image not contains full CUDA installation or libcuda.so located in some non standard path. Previously miner was require only CUDA runtime (static library) now anything much more complicated.
Thank you.

**Comment by renheren** [comment]
@xorz57 
With ccmake, I got the following options:
```
 ARM_TARGET                      *OFF
 BUILD_STATIC                    *OFF
 CMAKE_BUILD_TYPE                *
 CMAKE_INSTALL_PREFIX            */usr/local
 CUDA_ARCH                       *30;50;60;70
 CUDA_COMPILER                   *nvcc
 CUDA_HOST_COMPILER              */usr/bin/cc
 CUDA_KEEP_FILES                 *OFF
 CUDA_LIB                        *CUDA_LIB-NOTFOUND
 CUDA_NVRTC_LIB                  */usr/local/cuda/lib64/libnvrtc.so
 CUDA_SDK_ROOT_DIR               *CUDA_SDK_ROOT_DIR-NOTFOUND
 CUDA_SHOW_CODELINES             *OFF
 CUDA_SHOW_REGISTER              *OFF
 CUDA_TOOLKIT_ROOT_DIR           */usr/local/cuda
 CUDA_USE_STATIC_CUDA_RUNTIME    *ON
 CUDA_rt_LIBRARY                 */usr/lib/x86_64-linux-gnu/librt.so
 UV_INCLUDE_DIR                  */usr/include
 UV_LIBRARY                      */usr/lib/x86_64-linux-gnu/libuv.a
 WITH_AEON                       *ON
 WITH_ASM                        *ON
 WITH_CN_GPU                     *ON
 WITH_CN_PICO                    *ON
 WITH_DEBUG_LOG                  *OFF
 WITH_EMBEDDED_CONFIG            *OFF
 WITH_HTTPD                      *ON
 WITH_SUMO                       *ON
 WITH_TLS                        *ON
 XMR-STAK_LARGEGRID              *ON
```
still no cuda_lib is found.

**Comment by renheren** [comment]
@KnightZhao 
I've tried to do this in both "/usr/local/cuda/lib64" and "/usr/local/cuda/", still the same error. Maybe it's something else.

**Comment by xorz57** [comment]
@renheren at least now u can see all cmake variables. Maybe @xmrig can help you.

**Comment by renheren** [comment]
@xmrig 
I'm using nvidia/cuda:10.0-base image, no "libcuda.so" is found in "/usr/local/cuda/lib64", I'm going to check other image. A nice hint, thanks!

**Comment by renheren** [comment]
@xorz57 
Yes, thanks!

**Comment by renheren** [comment]
@xmrig 
I'm wrong, I was using devel image other than base image for compilation. So I don't know if it's easy to get a more complete cuda docker image.

**Comment by renheren** [comment]
@xmrig @xorz57 @KnightZhao
Update...
I've found "libcuda.so" in path of "/usr/local/cuda/lib64/stubs/libcuda.so". Sorry, I'm lost.

**Comment by renheren** [comment]
@xmrig @xorz57 @KnightZhao
Finally, I've solved my problem.
Just add option of "-DCUDA_LIB=/usr/local/cuda/lib64/stubs/libcuda.so" to cmake is enough for compilation.
Also, runtime image of cuda should be used instead of base image for execution to solve lackness of "libnvrtc.so.10.0".
Many Thanks!
