### ISSUE TITLE
DevFee pool job has very high difficulty

### ISSUE THREAD

**Issue by GrannyCryptomaster** [xmrig/xmrig-nvidia#254]
I use XMRig on a rig with 6x GTX 1060 3GB, hashing at 2730 H/s on CN-R algo. 
The devfee pool sends jobs at 1000xxx diff. I'm sure that you get no accepted shares at this huge diff in that short time that stays connected.
You should set a fix diff for devfee, according to miner's hashrate. HRx10 or HRx15 it's a very good choice.

**Comment by xmrig** [comment]
It's fine, only cumulative hashrate around all miners matters, your rig can find share with high diff in one of donation rounds (estimated every 6th round with 1 minute round), if your rig not found share, some one else will found it.
Thank you.
