### ISSUE TITLE
Fail to build with CUDA 9.0

### ISSUE THREAD

**Issue by calvintam236** [xmrig/xmrig-nvidia#26]
I went to upgrade the docker image of `xmrig-nvidia` using CUDA 9.0, but the build failed.

Build log: [here](https://hub.docker.com/r/calvintam236/xmrig-nvidia/builds/b7rfszdhhqr4gy8lbehc49r/)

Any idea how to fix that?

**Comment by xmrig** [comment]
Temporary solution: add `-DCUDA_ARCH="30;50;60"`.
Permanent solution: should check CUDA version, to build this list.
CUDA 9 doesn't support arch 20 (Fermi)
CUDA 7.5 doesn't support arch 60 (Pascal)

**Comment by calvintam236** [comment]
Thanks @xmrig . Maybe you can add this info to the build instructions at [https://github.com/xmrig/xmrig-nvidia/wiki/Ubuntu-Build](https://github.com/xmrig/xmrig-nvidia/wiki/Ubuntu-Build).
