### ISSUE TITLE
Plans for Xmrig Nvidia

### ISSUE THREAD

**Issue by Amf1k** [xmrig/xmrig-nvidia#299]
Hey. What are your plans for XmrigNvidia? Will it be as merged in Xmrig as XmrigAmd? or will it remain a separate repository?

**Comment by xmrig** [comment]
It will be integrated too, but for prebuilt binaries 2 versions will be available 2 in 1 (cpu+amd) and 3 in 1 (cpu + amd + nvidia), because CUDA requires a lot of external heavy dependencies.
Thank you.

**Comment by Amf1k** [comment]
when we will see all 3 miners in one repository? and stable version?

**Comment by xmrig** [comment]
Next beta release will be 4.4 (4.3 just released), one feature pending https://github.com/xmrig/xmrig/pull/1068 and it will be last major feature for v4 **about one week.**

**+ one week** (await bug-reports)

So next stable release v5 will available after about 2 weeks and will be based on v4.4.

For nvidia only very estimated time, before Monero fork.

**Comment by Amf1k** [comment]
thanks for answers
