### ISSUE TITLE
Error occurred while compiling with cuda 11 

### ISSUE THREAD

**Issue by PermissionDenied7335** [xmrig/xmrig-nvidia#310]
Building NVCC (Device) object CMakeFiles/xmrig-cuda.dir/src/nvidia/Release/xmrig-cuda_generated_cuda_core.cu.obj
nvcc fatal : Unsupported gpu architecture 'compute_30'
CMake Error at xmrig-cuda_generated_cuda_core.cu.obj.Release.cmake:220 (message):
Error generating
C:/Users/grade/xmrig-nvidia/build/CMakeFiles/xmrig-cuda.dir/src/nvidia/Release/xmrig-cuda_generated_cuda_core.cu.obj

**Comment by PermissionDenied7335** [comment]
Disable compute_30 support may work, but I don't know how to.

**Comment by sOblivionsCall** [comment]
also seeing the same issue, other similar issues comment compute_30 in cmake.config but i don't see that anywhere for this.

The root of the issue atleast for me appears to be that i am running a too new version of cuda (11) that has depricated compute_30. Am going to try to downgrade to cuda 10 and see how that goes

**Comment by sOblivionsCall** [comment]
that said this project hasn't been touched in 14 months so i am not hopeful to receive any kind of support.

**Comment by xmrig** [comment]
This project replaced by unified [xmrig](https://github.com/xmrig/xmrig) miner and [CUDA plugin](https://github.com/xmrig/xmrig-cuda) this bug already fixed https://github.com/xmrig/xmrig-cuda/commit/d483b2bfd2627db3884ee7ea6eaaf5ec100346a8 but you can specify cmake option `-DCUDA_ARCH=` it not require change the code https://github.com/xmrig/xmrig-nvidia/blob/master/cmake/CUDA.cmake#L48
Thank you.

**Comment by StefanL** [comment]
What he is trying to say is that the default cuda architecture built into the cmake scripts includes sm_30, compute_30, which is not supported by the cuda runtime and tools (sdk) after cuda 10.2, hence the error that you see `nvcc fatal : Unsupported gpu architecture 'compute_30'`.

The easy way to avoid this error is to specify the GPU architecture you want to target with the following:
`cmake .. -DCUDA_ARCH="40[;50;60]"`, where the multiple architectures in square brackets are optional.

Check the nvidia documentation to see what cuda version supports your video card, and what the compute capability of your card is and make sure they match.

For using older graphics cards with sm_30 or sm_20 specs you need to use older cuda sdks as well as older compilers (ie. gcc 7.5 and older). It gets complicated keeping all these different development environments straight.

**Comment by PermissionDenied7335** [comment]
It seems that I have solved the problem on my laptop but I forgot to close it. I'll close it anyway.
