### ISSUE TITLE
Could NOT find MHD (missing: MHD_LIBRARY MHD_INCLUDE_DIR)

### ISSUE THREAD

**Issue by LubomirBednar** [xmrig/xmrig-nvidia#324]
Hi. 
I am very new to this so I'll do my best to describe the issue. If it's lacking something please let me know.
I managed to install the xmrig and run it on my CPU. 
But when following the xmrig-nvidia guide for Windows build (https://github.com/xmrig/xmrig-nvidia/wiki/Windows-Build), I run into a error:

`-- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.19042.
-- Could NOT find MHD (missing: MHD_LIBRARY MHD_INCLUDE_DIR)
CMake Error at CMakeLists.txt:278 (message):
  microhttpd NOT found: use `-DWITH_HTTPD=OFF` to build without http deamon
  support`

I am attaching the cmake log as well. 
[CMakeError.log](https://github.com/xmrig/xmrig-nvidia/files/6010695/CMakeError.log)

Unfortunately I am not a programmer so I don't have the faintest clue what went wrong.

**Comment by xmrig** [comment]
https://github.com/xmrig/xmrig-nvidia/issues/310#issuecomment-706965450

**Comment by LubomirBednar** [comment]
Thank you! =]
