### ISSUE TITLE
Hashrate decrease on Nvidia 1060 GTX card with latest HEAD

### ISSUE THREAD

**Issue by mranostay** [xmrig/xmrig-nvidia#34]
On changeset cb881d74f3be37580d33f68b1a230d8910911406 I notice a 15 hash decrease on "EVGA GeForce GTX 1060 6GB FTW+ DT GAMING ACX 3.0, 6GB GDDR5, LED, DX12 OSD Support (PXOC) Graphics Card 06G-P4-6366-KR" but when reverted it goes back to 539 H/s

**Comment by xmrig** [comment]
You meant auto configuration gives suggest worse settings? It possible, new version suggest more threads (and more memory) to use, but hashrate/memory dependency it not linear. With equal settings should be no difference in hashrate. Did you use `config.json` where miner can write suggested settings?
Thank you.

**Comment by mranostay** [comment]
No I haven't used the json config but I can likely do that shortly to give results
