### ISSUE TITLE
Error on Nvidia Quadro M2200

### ISSUE THREAD

**Issue by mcsjohn** [xmrig/xmrig-nvidia#38]
Hello,

I get this error when trying to run xmrig-nvidia.
![image](https://user-images.githubusercontent.com/31309478/32457717-ba7d8b30-c332-11e7-8489-812d29768394.png)
Is xmrig-nvidia not supported on Nvidia Quadro or what is the problem?

Thanks

**Comment by CyborgGenos** [comment]
I get the exact same error with a Quadro K1200. I'm certain that the card is capable of handling cryptonight because it works with nicehash for mining zcash. But I really want to mine monero now and I cannot because of this error. Please help

**Comment by xmrig** [comment]
Try decrease threads count and/or bfactor in config file.
Thank you.

**Comment by CyborgGenos** [comment]
Thank you very much, I looked at the values for the zcash miner and it used 16 Blocks and 8 Threads. By default xmrig was set to 64 threads and 12 blocks so I just changed those values in the config.json file to match zcash and now it's working. Thank you very much, I'm increasing my donation level :grin: 😁

**Comment by mcsjohn** [comment]
Thanks! It worked also in my case. By default xmrig-nvidia was trying with 42 threads. I have tried lower values and looks like best performance for Quadro M2200 is with 16 threads. It works with more also but performance decreases. At 32 threads same error.

**Comment by xiaohuimc** [comment]
* VERSIONS:     XMRig/2.4.2 libuv/1.9.1 CUDA/9.10 MSVC/2015
 * CPU:          Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz x64 AES-NI
 * GPU #0:       GeForce GTX 950M @ 1124/1001 MHz 64x15 6x25 arch:50 SMX:5
 * ALGO:         cryptonight, donate=5%
 * POOL #1:      xmr.crypto-pool.fr:3333
 * COMMANDS:     hashrate, health, pause, resume
[2017-12-30 19:14:28] use pool xmr.crypto-pool.fr:3333 163.172.207.71
[2017-12-30 19:14:28] new job from xmr.crypto-pool.fr:3333 diff 18000
[CUDA] Error gpu 0: <cryptonight_extra_cpu_final>:231 "unspecified launch failure"


Reduce the same error as the thread
