### ISSUE TITLE
Problems with gcc

### ISSUE THREAD

**Issue by crlsgms** [xmrig/xmrig-nvidia#41]
Hello everyone

Im trying to compile the nvidia version, but with the debian machines I have arround I have gcc 4.9 on 8 and 6.x on 9. I setup a virtual machine with ubuntu just to compile the binaries, but with no sucess

Is there anyway to compile any version of the xmrig-nvidia with versions 4.9 or 6 from gcc, since the 5.x version isn't avaiable on regular repos?

thanks

**Comment by xmrig** [comment]
CUDA has very strict requirements for compiler version, miner code itself support gcc 4.9+ but CUDA not.
Thank you.
