### ISSUE TITLE
config

### ISSUE THREAD

**Issue by rawr123** [xmrig/xmrig-nvidia#42]
How would you set up the config for xmrpool.net?

Trying to sign in after getting shares, and it says wrong password. :\

**Comment by xmrig** [comment]
It common issue for all nodejs-pool based pools, check config generator https://supportxmr.com/#/help/config_generator

Actually sign in not required, until you want increase payout limits or get email notifications.
Thank you.

**Comment by rawr123** [comment]
Thanks a lot!
