### ISSUE TITLE
 [CUDA] Error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by dimin75** [xmrig/xmrig-nvidia#48]
Hello there.
I'm trying to launch xmrig-nvidia using Fedora26 with Cuda 9.
Nvidia-Drivers version is 384.98 - probably latest one.
After successful compiling having an issue:
--------------------------------------------------------------------------------------------------------------------
 * VERSIONS:     XMRig/2.4.2 libuv/1.11.0 CUDA/9.0 gcc/6.4.1
 * CPU:          AMD Athlon(tm) II X2 250 Processor (1) x64 -AES-NI
 * GPU #0:       GeForce GTX 750 Ti @ 1800/2052 MHz 62x8 0x0 arch:21 SMX:4
 * ALGO:         cryptonight, donate=1%
 * POOL #1:      bytecoin.uk:7777
 * COMMANDS:     'h' hashrate, 'e' health, 'p' pause, 'r' resume
[2017-11-19 01:38:33] use pool bytecoin.uk:7777 158.69.143.62
[2017-11-19 01:38:33] new job from bytecoin.uk:7777 diff 1063
[CUDA] Error gpu 0: <cryptonight_extra_cpu_prepare>:215 "no kernel image is available for execution on the device"
terminate called after throwing an instance of 'std::runtime_error'
  what():  [CUDA] Error: no kernel image is available for execution on the device
Aborted
--------------------------------------------------------------------------------------------------------------------
same problem with missing kernel has an xmr-stak-nvidia.
Meanwhile mining client made by minergate(dot)com for fedora25 works on this system.

Any ideas what to do?

**Comment by virsystem** [comment]
have some too..
Win7x64
driver 388
cuda 9
gtx570

**Comment by xmrig** [comment]
Please use CUDA8, both card not supported by CUDA9.
For Windows, cuda8 release also available.
Thank you.

**Comment by dimin75** [comment]
Ok. I think it is time to close this issue. Finally solution has been found.
The main problem that even GPU-card is marked as GTX 750 Ti it does not have an architecture 50 
(actually 21, as shown at first message of issue). Even when I installed to fedora 26 Cuda 8.0, problem
was still the same. 
Well, probably actual solution for Fedora is separate installation of gcc 5.3 & g++-5. But for this purposes someone should get src of compiler and assembly it for Fedora.  It is not very simple for
novices and non-linux users.
So my solution was use UBUNTU 17.04 instead of Fedora 26. 
Installation of NVIDIA-drivers and CUDA was fully described at 
https://github.com/xmrig/xmrig-nvidia/wiki
There were no problem to follow by manual.

Now this card works properly under UBUNTU.
Hashrate is not very different with the Windows, almost the same.

With best wishes,
Dmitry.
