### ISSUE TITLE
Unspecified Launch Failure

### ISSUE THREAD

**Issue by xorz57** [xmrig/xmrig-nvidia#49]
![image](https://user-images.githubusercontent.com/1548352/32983768-cabb38b6-cca2-11e7-8c57-9df933c51008.png)

**Comment by ILLuMiNaTe7** [comment]
Exactly the same issue.

**Comment by xorz57** [comment]
@ILLuMiNaTe7 I guess this has to do with the WDDM TDR Delay when a CUDA kernel takes over 2 secs to start itself.

**Comment by ILLuMiNaTe7** [comment]
@xorz57 Well no clue what the issue was. But i have resolved it by picking an older release.

**Comment by xmrig** [comment]
Reduce `threads` options and/or increase `bfactor`. Older release use maximum 32 threads in any case. To simulate this old behavior, use command line option `--cuda-max-threads=32` or config option `"cuda-max-threads": 32,`.

If you place config.json near executable, this file will be updated with suggested values.
You may need tune it. For GTX 1070 probably better use 32 threads (or so) instead of 64.
Thank you for reports, auto config need be fixed again.

**Comment by HydraGene** [comment]
I still keep getting this error, even with threads at 32 or with option `--cuda-max-threads=32`. I don't see `"cuda-max-threads": 32,` in the config.json anywhere.. Where should I put it?
Running the older version 2.3.1 doesn't solve my problem.
I am running Windows10, i7-5700HQ, GTX 960M.
Any idea about what could be wrong?

**Comment by xorz57** [comment]
@HydraGene As I said above this most probably happens due to the WDDM TDR Delay which is 2 seconds by default. I on Linux there should be no problem at all.

**Comment by xorz57** [comment]
![image](https://user-images.githubusercontent.com/1548352/33155914-49ebe86c-cffd-11e7-91f9-5fcf03aba61c.png)
I have been experimenting with the CUDA API for a while and this is how I typically resolve this error.
Read the description of what is WDDM.

**Comment by HydraGene** [comment]
@xorz57 Thanks for the info. I'll read that.
In the meantime I have been told to set `bfactor` to `8`. This has solved the issue for me. I am mining now.

**Comment by Skroy41** [comment]
Hi,

where do you set up those commands ??? In the bat file ???, are you on windows or linux ???

**Comment by xorz57** [comment]
@Skroy41 This happens only on windows os for the reasons I stated above.

**Comment by Skroy41** [comment]
OK thanks xorz57, can you help me and tell me where to set those commands :+1: 

set bfactor to 8
--cuda-max-threads=32
"cuda-max-threads": 32

where do I set those command ?? In the .BAT file ??? or anywhere else ?

also where can I find and open the Nvidia Nsight Options ???
Sorry I am still beginners in minning set ups.

thanks, for your precious help

**Comment by xorz57** [comment]
@Skroy41 First things first, in order to use the NVidia NSight you have to install NVidia CUDA toolkit. The "commands" you are asking for are none else than `command line arguments` passed directly after the application name when you launch a `powershell/cmd` in the project directory. There is no need to place these "commands" inside a batch file.

**Comment by Skroy41** [comment]
Thanks xor57, but you are too complex for me ???

"The "commands" you are asking for are none else than command line arguments passed directly after the application name when you launch a powershell/cmd in the project directory"

this is chinese for me : Is that mean that I open powershell if not, what is the "project Directory" and how to access it in powershell ???

also my Nvidia Nsight option is not like yours,

don't have a all the options u got.

first I just have  "general" (no analysis, suda etc....)


![image](https://user-images.githubusercontent.com/36062332/35773732-856ea6ea-095a-11e8-8579-cbcb46f7db2a.png)
