### ISSUE TITLE
please add cryptonight-lite

### ISSUE THREAD

**Issue by fabheros** [xmrig/xmrig-nvidia#5]
it's for aeoncoin mining please

**Comment by fabheros** [comment]
it's for aeoncoin mining please

**Comment by xmrig** [comment]
Yep I know about AEON, it planned.
Thank you.

**Comment by dorimanx** [comment]
Please release new Win BETA for us :) i see you have already added AEON... need to mine :)
Thanks.

**Comment by xmrig** [comment]
I made v2.3.0 release.

**Comment by fabheros** [comment]
Thank you very much, xmrig is great !
