### ISSUE TITLE
Error compiling on Windows 10 with msvc 2017

### ISSUE THREAD

**Issue by coen800** [xmrig/xmrig-nvidia#55]
When i try to compile i get tis error: C:\xmrig-nvidia-master\build>cmake .. -G "Visual Studio 15 2017 Win64" -T v140,host=x64 -DUV_INCLUDE_DIR="c:\deps\msvc2015\libuv\x64\include" -DUV_LIBRARY="c:\deps\msvc2015\libuv\x64\lib\libuv.lib" -DMHD_INCLUDE_DIR="c:\deps\msvc2015\libmicrohttpd\x64\include" -DMHD_LIBRARY="c:\deps\msvc2015\libmicrohttpd\x64\lib\libmicrohttpd.lib" -DWITH_AEON=OFF -DWITH_HTTPD=OFF
CMake Error at CMakeLists.txt:2 (project):
  Failed to run MSBuild command:

    C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/MSBuild/15.0/Bin/MSBuild.exe

  to get the value of VCTargetsPath:

    Microsoft (R) Build Engine version 15.4.8.50001 for .NET Framework
    Copyright (C) Microsoft Corporation. All rights reserved.

    Build started 5-12-2017 10:34:38.
    Project "C:\xmrig-nvidia-master\build\CMakeFiles\3.10.0\VCTargetsPath.vcxproj" on node 1 (default targets).
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.Cpp.Platform.targets(57,5): error MSB8020: The build tools for v140 (Platform Toolset = 'v140') cannot be found. To build using the v140 build tools, please install v140 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution". [C:\xmrig-nvidia-master\build\CMakeFiles\3.10.0\VCTargetsPath.vcxproj]
    Done Building Project "C:\xmrig-nvidia-master\build\CMakeFiles\3.10.0\VCTargetsPath.vcxproj" (default targets) -- FAILED.

    Build FAILED.

    "C:\xmrig-nvidia-master\build\CMakeFiles\3.10.0\VCTargetsPath.vcxproj" (default target) (1) ->
    (PlatformPrepareForBuild target) ->
      C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.Cpp.Platform.targets(57,5): error MSB8020: The build tools for v140 (Platform Toolset = 'v140') cannot be found. To build using the v140 build tools, please install v140 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution". [C:\xmrig-nvidia-master\build\CMakeFiles\3.10.0\VCTargetsPath.vcxproj]

        0 Warning(s)
        1 Error(s)

    Time Elapsed 00:00:00.17

  Exit code: 1

-- Configuring incomplete, errors occurred!
See also "C:/xmrig-nvidia-master/build/CMakeFiles/CMakeOutput.log".
This is in CMakeOutpout.log: 
The system is: Windows - 10.0.16299 - AMD64

**Comment by DarkIsmael** [comment]
Install the current VC++ 2017 toolset and it will work

**Comment by coen800** [comment]
Still doesn't work same error
