### ISSUE TITLE
Error when compiling xmrig-nvidia "Unable to open input file "Release\xmrig-cuda.lib""

### ISSUE THREAD

**Issue by kent9876** [xmrig/xmrig-nvidia#66]
Well,  main part in name of the thread. Here mine screenshot:
![image](https://user-images.githubusercontent.com/32428318/34155340-ac8d5b4c-e504-11e7-98cf-497c76f88c5d.png)
Do not look at localization) *RU
VS 2015 T_140
Win 10 X64
CMake x64
Nvidia toolset installed properly
libuv x64
http not using
cmake .. -G "Visual Studio 14 2015 Win64" -T v140,host=x64 -DUV_INCLUDE_DIR="C:\libuv\x64\include" -DUV_LIBRARY="C:\libuv\x64\lib\libuv.lib"  -DWITH_HTTPD=OFF

**Comment by asc99c** [comment]
I'm currently struggling with a similar issue.  Although I think in your case, device_functions.hpp is the problem - it's an incompatibility with your version of CUDA.  If you pull in the latest changes, I think that is fixed (renamed to device_functions.h).

**Comment by n0file** [comment]
Нашёл решение?

**Comment by n0file** [comment]
![image](https://user-images.githubusercontent.com/36566127/36351778-c700c352-14bf-11e8-8a86-4930da91de31.png)
Интересные ты файлики хранишь
С дв? =)

**Comment by oookotooo** [comment]
+1

**Comment by oookotooo** [comment]
fatal error LNK1181: не удается открыть входной файл "Release\xmrig-cuda.lib"

**Comment by n0file** [comment]
@oookotooo Если найдёшь решение, пиши сюда :0

**Comment by oookotooo** [comment]
Why closed? Help to fix, please!
