### ISSUE TITLE
Miner Opens then Immediately Closes with no Error messages

### ISSUE THREAD

**Issue by wildlifedave** [xmrig/xmrig-nvidia#72]
The miner seems to open for a split second then closes immediately without giving any sort of error message. I have altered many settings but it seems to have the same effect every time. 

My config.json file...

{
    "algo": "cryptonight",
    "background": false,
    "colors": true,
    "donate-level": 1,
    "log-file": null,
    "print-time": 60,
    "retries": 5,
    "retry-pause": 5,
    "syslog": false,
    "threads": null,
    "pools": [
        {
            "url": "mine.xmrpool.net:5557",
            "user": "",
            "pass": "x",
            "keepalive": true,
            "nicehash": false
        }
    ]
}

I'm completely confused with this NVIDIA miner - I've successfully set up a CPU miner with no problems. If anyone has any ideas on how to resolve this, I'd greatly appreciate it.

**Comment by Wra1th7** [comment]
Hi
I am having the exact same problem & have tried both cuda8/cuda9 versions with same details in the json file.

I managed to see something about gpu0 & then the miner closes

**Comment by pinkygigabyte** [comment]
hi... i have same problem at a 960m GTX.

**Comment by lismanb** [comment]
do you start it in background mode?
In my case it stops only when I try to run it in background mode.

**Comment by pinkygigabyte** [comment]
in all modes my miner crash same at Wildlifedave

**Comment by pinkygigabyte** [comment]
I installed lastest CUDA 9 (was CUDA 7.5 before), and i set threads: 8 and blocks: 30 at my 960m GTX, and now work fine at 255 h/s

**Comment by brentmclark** [comment]
Make sure you are running the miner from the command line on Windows machines.  If you double-click the exe it will open, and then immediately close, the command window.

**Comment by wildlifedave** [comment]
thank you @brentmclark - that was the solution. Though I do have a CUDA issue to work through. But simply opening command line and putting in the path for the .exe and hitting enter did the trick and kept the window open. Thank you for your assistance.

**Comment by guh0jason** [comment]
wich is the command line ???
