### ISSUE TITLE
Can't build with CryptoNight-Lite support OFF

### ISSUE THREAD

**Issue by esfomeado** [xmrig/xmrig-nvidia#8]
CudaWorker.cpp(56): error C3861: 'cryptonight_gpu_init_lite': identifier not found
CudaWorker.cpp(84): error C3861: 'cryptonight_gpu_hash_lite': identifier not found
CryptoNight.cpp(122): error C2065: 'test_output1': undeclared identifier
CryptoNight.cpp(122): error C2660: 'memcmp': function does not take 2 arguments

**Comment by xmrig** [comment]
Fixed.
Thank you.

**Comment by esfomeado** [comment]
Building fine now :)
