### ISSUE TITLE
Trojan:Win32/Bluteal!rfn in Nvidia binary cuda 8 and cuda 9

### ISSUE THREAD

**Issue by dazsim** [xmrig/xmrig-nvidia#88]
as the title suggests both versions reporting trojans on windows defender

**Comment by realKSMC** [comment]
Agree, please fix.

**Comment by metalurgus** [comment]
I think it is Windows Defender problem

**Comment by dazsim** [comment]
Then why is it the second false positive on this project? This isn't the first time people have reported problems with Trojan alerts

**Comment by metalurgus** [comment]
most part of miners are concidered as virus alerts. Just because the apps that contain mining algorithms in most cases are viruses. But you here have the sources. You can check them for viruses by yourself, and build your own binary, which can't have viruses by definition.
