### ISSUE TITLE
MVS 2017 Build xmrig-cuda

### ISSUE THREAD

**Issue by ppereirasky** [xmrig/xmrig-nvidia#92]
Hi There,

I have followed the Windows Build instructions. My cmake is 3.10 - MVS 2017 Community Edition with the v140 extra installed / Windows 10 x64.
I had to add to cmake -DCUDA_TOOLKIT_ROOT_DIR="C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.1" because it was not finding CUDA

cmake works well - only with a missing file:
-- Looking for syslog.h - not found

When I open xmrig-nvidia.sln and try to build xmrig-cuda it fails with:
1>------ Build started: Project: xmrig-cuda, Configuration: Release x64 ------
1>Building NVCC (Device) object CMakeFiles/xmrig-cuda.dir/src/nvidia/Release/xmrig-cuda_generated_cuda_core.cu.obj
1>nvcc fatal   : Could not set up the environment for Microsoft Visual Studio using 'C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/../../VC/bin/amd64/vcvars64.bat'
1>CMake Error at xmrig-cuda_generated_cuda_core.cu.obj.Release.cmake:219 (message):
1>  Error generating
1>  D:/MINING/xmrig-nvidia-master/build/CMakeFiles/xmrig-cuda.dir/src/nvidia/Release/xmrig-cuda_generated_cuda_core.cu.obj
1>
1>
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code 1.
1>Done building project "xmrig-cuda.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 1 up-to-date, 0 skipped ==========

Can anyone help?

Best Regards

**Comment by garrylachman** [comment]
same here...

**Comment by metalurgus** [comment]
Which version of visual studio are you using?

**Comment by garrylachman** [comment]
2017 just updated 

---- On Wed, 31 Jan 2018 15:38:07 +0200 notifications@github.com wrote ----

Which version of visual studio are you using?

**Comment by metalurgus** [comment]
that's not the version. that's a part of product name `Visual Studio 2017`. The version can be 15.x.x
And one of the latest versions is bugged, and can't build xmrig. Use 15.4.5

**Comment by garrylachman** [comment]
i use 15.5.6

**Comment by metalurgus** [comment]
That version is probably the bugged one. Try 15.4.5

**Comment by n0file** [comment]
So what was the solution?
