### ISSUE TITLE
V2.4.2-Cuda9 release download issue

### ISSUE THREAD

**Issue by Aldude** [xmrig/xmrig-nvidia#97]
The file xmrig-nvidia-2.4.2-cuda8-win64.zip downloads perfectly fine but xmrig-nvidia-2.4.2-cuda9-win64.zip gets labelled as dangerous and is blocked by Chrome.

**Comment by metalurgus** [comment]
This is not an issue as for me. That is because Chrome treats all applications that contain mining code as dangerous. You may just download it using other downloader. Or just go to all downloads in Chrome, and press allow, or something like that
